//Interneuron Synapse

//Copyright(C) 2021  Interneuron CIC

//This program is free software: you can redistribute it and/or modify
//it under the terms of the GNU General Public License as published by
//the Free Software Foundation, either version 3 of the License, or
//(at your option) any later version.

//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

//See the
//GNU General Public License for more details.

//You should have received a copy of the GNU General Public License
//along with this program.If not, see<http://www.gnu.org/licenses/>.


﻿using System;
using Microsoft.EntityFrameworkCore;
using Interneuron.CareRecord.Model.DomainModels;
using Microsoft.EntityFrameworkCore.Metadata;
using Interneuron.CareRecord.Repository;
using Microsoft.Extensions.Configuration;

namespace Interneuron.CareRecord.Repository.DBModelsContext
{
    public partial class SynapseDBContext
    {

        public virtual DbSet<baseview_AneAne> baseview_AneAne { get; set; }
        public virtual DbSet<baseview_AneAnegreaterthan4hours> baseview_AneAnegreaterthan4hours { get; set; }
        public virtual DbSet<baseview_AneRecentlydischarged> baseview_AneRecentlydischarged { get; set; }
        public virtual DbSet<baseview_AutonomicObservationevent> baseview_AutonomicObservationevent { get; set; }
        public virtual DbSet<baseview_BvCoreFluidbalancechart> baseview_BvCoreFluidbalancechart { get; set; }
        public virtual DbSet<baseview_BvCoreFluidbalanceobservationhistory> baseview_BvCoreFluidbalanceobservationhistory { get; set; }
        public virtual DbSet<baseview_BvCoreFutureappointments> baseview_BvCoreFutureappointments { get; set; }
        public virtual DbSet<baseview_BvCoreInpatientappointments> baseview_BvCoreInpatientappointments { get; set; }
        public virtual DbSet<baseview_BvCoreInpatientencountersforfluidbalance> baseview_BvCoreInpatientencountersforfluidbalance { get; set; }
        public virtual DbSet<baseview_BvCoreIntakefluidbalanceevents> baseview_BvCoreIntakefluidbalanceevents { get; set; }
        public virtual DbSet<baseview_BvCoreOutputfluidbalanceevents> baseview_BvCoreOutputfluidbalanceevents { get; set; }
        public virtual DbSet<baseview_BvCorePersonwithids> baseview_BvCorePersonwithids { get; set; }
        public virtual DbSet<baseview_CarerecordDemographics> baseview_CarerecordDemographics { get; set; }
        public virtual DbSet<baseview_CarerecordObservations> baseview_CarerecordObservations { get; set; }
        public virtual DbSet<baseview_CarerecordResults> baseview_CarerecordResults { get; set; }
        public virtual DbSet<baseview_CofAdmintasklist> baseview_CofAdmintasklist { get; set; }
        public virtual DbSet<baseview_CofAppointmenthistory> baseview_CofAppointmenthistory { get; set; }
        public virtual DbSet<baseview_CofAppointmenthistorynew> baseview_CofAppointmenthistorynew { get; set; }
        public virtual DbSet<baseview_CofAppointmentswithlookups> baseview_CofAppointmentswithlookups { get; set; }
        public virtual DbSet<baseview_CofCofappointmentlist> baseview_CofCofappointmentlist { get; set; }
        public virtual DbSet<baseview_CofIncorrectrttreport> baseview_CofIncorrectrttreport { get; set; }
        public virtual DbSet<baseview_CofNewtasklist> baseview_CofNewtasklist { get; set; }
        public virtual DbSet<baseview_CofOpappointmenthistory> baseview_CofOpappointmenthistory { get; set; }
        public virtual DbSet<baseview_CofPatientbannerfinal> baseview_CofPatientbannerfinal { get; set; }
        public virtual DbSet<entitystore_CoreAllergyintollerance> entitystore_CoreAllergyintollerance { get; set; }
        public virtual DbSet<entitystorematerialised_CoreAllergyintollerance1> entitystorematerialised_CoreAllergyintollerance1 { get; set; }
        public virtual DbSet<entitystore_CoreCarerecord> entitystore_CoreCarerecord { get; set; }
        public virtual DbSet<entitystorematerialised_CoreCarerecord1> entitystorematerialised_CoreCarerecord1 { get; set; }
        public virtual DbSet<entitystore_CoreDemoentity> entitystore_CoreDemoentity { get; set; }
        public virtual DbSet<entitystorematerialised_CoreDemoentity1> entitystorematerialised_CoreDemoentity1 { get; set; }
        public virtual DbSet<entitystore_CoreDocuments> entitystore_CoreDocuments { get; set; }
        public virtual DbSet<entitystorematerialised_CoreDocuments1> entitystorematerialised_CoreDocuments1 { get; set; }
        public virtual DbSet<entitystore_CoreDocumentsrepository> entitystore_CoreDocumentsrepository { get; set; }
        public virtual DbSet<entitystorematerialised_CoreDocumentsrepository1> entitystorematerialised_CoreDocumentsrepository1 { get; set; }
        public virtual DbSet<entitystorematerialised_CoreEncounter> entitystorematerialised_CoreEncounter { get; set; }
        public virtual DbSet<entitystore_CoreEncounter1> entitystore_CoreEncounter1 { get; set; }
        public virtual DbSet<entitystore_CoreFluidbalancechart> entitystore_CoreFluidbalancechart { get; set; }
        public virtual DbSet<entitystorematerialised_CoreFluidbalancechart1> entitystorematerialised_CoreFluidbalancechart1 { get; set; }
        public virtual DbSet<entitystorematerialised_CoreFluidbalanceevent> entitystorematerialised_CoreFluidbalanceevent { get; set; }
        public virtual DbSet<entitystore_CoreFluidbalanceevent1> entitystore_CoreFluidbalanceevent1 { get; set; }
        public virtual DbSet<entitystore_CoreFluidbalanceobservation> entitystore_CoreFluidbalanceobservation { get; set; }
        public virtual DbSet<entitystorematerialised_CoreFluidbalanceobservation1> entitystorematerialised_CoreFluidbalanceobservation1 { get; set; }
        public virtual DbSet<entitystore_CoreList> entitystore_CoreList { get; set; }
        public virtual DbSet<entitystorematerialised_CoreList1> entitystorematerialised_CoreList1 { get; set; }
        public virtual DbSet<entitystore_CoreListquestion> entitystore_CoreListquestion { get; set; }
        public virtual DbSet<entitystorematerialised_CoreListquestion1> entitystorematerialised_CoreListquestion1 { get; set; }
        public virtual DbSet<entitystore_CoreListquestionvalue> entitystore_CoreListquestionvalue { get; set; }
        public virtual DbSet<entitystorematerialised_CoreListquestionvalue1> entitystorematerialised_CoreListquestionvalue1 { get; set; }
        public virtual DbSet<entitystore_CoreLookup> entitystore_CoreLookup { get; set; }
        public virtual DbSet<entitystore_CoreNextofkin> entitystore_CoreNextofkin { get; set; }
        public virtual DbSet<entitystorematerialised_CoreNextofkin1> entitystorematerialised_CoreNextofkin1 { get; set; }
        public virtual DbSet<entitystore_CoreNote> entitystore_CoreNote { get; set; }
        public virtual DbSet<entitystorematerialised_CoreNote1> entitystorematerialised_CoreNote1 { get; set; }
        public virtual DbSet<entitystorematerialised_CoreObservation> entitystorematerialised_CoreObservation { get; set; }
        public virtual DbSet<entitystore_CoreObservation1> entitystore_CoreObservation1 { get; set; }
        public virtual DbSet<entitystorematerialised_CoreObservationevent> entitystorematerialised_CoreObservationevent { get; set; }
        public virtual DbSet<entitystore_CoreObservationevent1> entitystore_CoreObservationevent1 { get; set; }
        public virtual DbSet<entitystore_CoreOrder> entitystore_CoreOrder { get; set; }
        public virtual DbSet<entitystorematerialised_CoreOrder1> entitystorematerialised_CoreOrder1 { get; set; }
        public virtual DbSet<entitystorematerialised_CorePerson> entitystorematerialised_CorePerson { get; set; }
        public virtual DbSet<entitystore_CorePerson1> entitystore_CorePerson1 { get; set; }
        public virtual DbSet<entitystore_CorePersonOld> entitystore_CorePersonOld { get; set; }
        public virtual DbSet<entitystore_CorePersonaddress> entitystore_CorePersonaddress { get; set; }
        public virtual DbSet<entitystorematerialised_CorePersonaddress1> entitystorematerialised_CorePersonaddress1 { get; set; }
        public virtual DbSet<entitystore_CorePersonaddresstype> entitystore_CorePersonaddresstype { get; set; }
        public virtual DbSet<entitystorematerialised_CorePersonaddresstype1> entitystorematerialised_CorePersonaddresstype1 { get; set; }
        public virtual DbSet<entitystore_CorePersoncontactinfo> entitystore_CorePersoncontactinfo { get; set; }
        public virtual DbSet<entitystorematerialised_CorePersoncontactinfo1> entitystorematerialised_CorePersoncontactinfo1 { get; set; }
        public virtual DbSet<entitystorematerialised_CorePersonidentifier> entitystorematerialised_CorePersonidentifier { get; set; }
        public virtual DbSet<entitystore_CorePersonidentifier1> entitystore_CorePersonidentifier1 { get; set; }
        public virtual DbSet<entitystore_CorePersonobservationscale> entitystore_CorePersonobservationscale { get; set; }
        public virtual DbSet<entitystorematerialised_CorePersonobservationscale1> entitystorematerialised_CorePersonobservationscale1 { get; set; }
        public virtual DbSet<entitystorematerialised_CoreProcedure> entitystorematerialised_CoreProcedure { get; set; }
        public virtual DbSet<entitystore_CoreProcedure1> entitystore_CoreProcedure1 { get; set; }
        public virtual DbSet<entitystore_CoreProvider> entitystore_CoreProvider { get; set; }
        public virtual DbSet<entitystorematerialised_CoreProvider1> entitystorematerialised_CoreProvider1 { get; set; }
        public virtual DbSet<entitystore_CoreProviderteam> entitystore_CoreProviderteam { get; set; }
        public virtual DbSet<entitystorematerialised_CoreProviderteam1> entitystorematerialised_CoreProviderteam1 { get; set; }
        public virtual DbSet<entitystore_CoreProviderteammembership> entitystore_CoreProviderteammembership { get; set; }
        public virtual DbSet<entitystorematerialised_CoreProviderteammembership1> entitystorematerialised_CoreProviderteammembership1 { get; set; }
        public virtual DbSet<entitystore_CoreQuestion> entitystore_CoreQuestion { get; set; }
        public virtual DbSet<entitystorematerialised_CoreQuestion1> entitystorematerialised_CoreQuestion1 { get; set; }
        public virtual DbSet<entitystorematerialised_CoreReferral> entitystorematerialised_CoreReferral { get; set; }
        public virtual DbSet<entitystore_CoreReferral1> entitystore_CoreReferral1 { get; set; }
        public virtual DbSet<entitystore_CoreReferralprovider> entitystore_CoreReferralprovider { get; set; }
        public virtual DbSet<entitystorematerialised_CoreReferralprovider1> entitystorematerialised_CoreReferralprovider1 { get; set; }
        public virtual DbSet<entitystore_CoreResult> entitystore_CoreResult { get; set; }
        public virtual DbSet<entitystorematerialised_CoreResult1> entitystorematerialised_CoreResult1 { get; set; }
        public virtual DbSet<entitystorematerialised_CoreScore> entitystorematerialised_CoreScore { get; set; }
        public virtual DbSet<entitystore_CoreScore1> entitystore_CoreScore1 { get; set; }
        public virtual DbSet<entitystore_CoreTheatresession> entitystore_CoreTheatresession { get; set; }
        public virtual DbSet<entitystorematerialised_CoreTheatresession1> entitystorematerialised_CoreTheatresession1 { get; set; }
        public virtual DbSet<entitystore_CoreTheatresessionprovider> entitystore_CoreTheatresessionprovider { get; set; }
        public virtual DbSet<entitystorematerialised_CoreTheatresessionprovider1> entitystorematerialised_CoreTheatresessionprovider1 { get; set; }
        public virtual DbSet<baseview_DcsEnrolledpatients> baseview_DcsEnrolledpatients { get; set; }
        public virtual DbSet<entitystore_DcsForm> entitystore_DcsForm { get; set; }
        public virtual DbSet<entitystorematerialised_DcsForm1> entitystorematerialised_DcsForm1 { get; set; }
        public virtual DbSet<entitystore_DcsForminstance> entitystore_DcsForminstance { get; set; }
        public virtual DbSet<entitystorematerialised_DcsForminstance1> entitystorematerialised_DcsForminstance1 { get; set; }
        public virtual DbSet<entitystore_DcsFormresponse> entitystore_DcsFormresponse { get; set; }
        public virtual DbSet<entitystorematerialised_DcsFormresponse1> entitystorematerialised_DcsFormresponse1 { get; set; }
        public virtual DbSet<entitystore_DcsFormscore> entitystore_DcsFormscore { get; set; }
        public virtual DbSet<entitystorematerialised_DcsFormscore1> entitystorematerialised_DcsFormscore1 { get; set; }
        public virtual DbSet<baseview_DcsOutpatientandreferralappointment> baseview_DcsOutpatientandreferralappointment { get; set; }
        public virtual DbSet<entitystore_DcsPatientregistration> entitystore_DcsPatientregistration { get; set; }
        public virtual DbSet<entitystorematerialised_DcsPatientregistration1> entitystorematerialised_DcsPatientregistration1 { get; set; }
        public virtual DbSet<baseview_DemoBedboard> baseview_DemoBedboard { get; set; }
        public virtual DbSet<baseview_DemoDemo2> baseview_DemoDemo2 { get; set; }
        public virtual DbSet<baseview_DemoDemosampleview1> baseview_DemoDemosampleview1 { get; set; }
        public virtual DbSet<baseview_DemoLocaldemosampleentity1view1> baseview_DemoLocaldemosampleentity1view1 { get; set; }
        public virtual DbSet<baseview_DemoNjrworklist> baseview_DemoNjrworklist { get; set; }
        public virtual DbSet<baseview_DemoPatientcontactdetails> baseview_DemoPatientcontactdetails { get; set; }
        public virtual DbSet<baseview_DemoPatientinfoc1> baseview_DemoPatientinfoc1 { get; set; }
        public virtual DbSet<baseview_DemoUszdemo> baseview_DemoUszdemo { get; set; }
        public virtual DbSet<baseview_EboardsBcpexport> baseview_EboardsBcpexport { get; set; }
        public virtual DbSet<baseview_EboardsCurrentinpatientbeds> baseview_EboardsCurrentinpatientbeds { get; set; }
        public virtual DbSet<baseview_EboardsEncounteridd> baseview_EboardsEncounteridd { get; set; }
        public virtual DbSet<baseview_EboardsWardswithwaitingarea> baseview_EboardsWardswithwaitingarea { get; set; }
        public virtual DbSet<entitystore_ExtendedEncounter> entitystore_ExtendedEncounter { get; set; }
        public virtual DbSet<entitystorematerialised_ExtendedEncounter1> entitystorematerialised_ExtendedEncounter1 { get; set; }
        public virtual DbSet<entitystore_ExtendedPerson> entitystore_ExtendedPerson { get; set; }
        public virtual DbSet<entitystorematerialised_ExtendedPerson1> entitystorematerialised_ExtendedPerson1 { get; set; }
        public virtual DbSet<baseview_ListBinarycheckboxvalueswithcontext> baseview_ListBinarycheckboxvalueswithcontext { get; set; }
        public virtual DbSet<baseview_ListDatewithcontext> baseview_ListDatewithcontext { get; set; }
        public virtual DbSet<baseview_ListLongtextwithcontext> baseview_ListLongtextwithcontext { get; set; }
        public virtual DbSet<baseview_ListSelectradiovalueswithcontext> baseview_ListSelectradiovalueswithcontext { get; set; }
        public virtual DbSet<baseview_ListShorttextwithcontext> baseview_ListShorttextwithcontext { get; set; }
        public virtual DbSet<baseview_ListsAlllists> baseview_ListsAlllists { get; set; }
        public virtual DbSet<entitystore_LocalAneClinicalnotes> entitystore_LocalAneClinicalnotes { get; set; }
        public virtual DbSet<entitystorematerialised_LocalAneClinicalnotes1> entitystorematerialised_LocalAneClinicalnotes1 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalAneCoding> entitystorematerialised_LocalAneCoding { get; set; }
        public virtual DbSet<entitystore_LocalAneCoding1> entitystore_LocalAneCoding1 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalAneEncounter> entitystorematerialised_LocalAneEncounter { get; set; }
        public virtual DbSet<entitystore_LocalAneEncounter1> entitystore_LocalAneEncounter1 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofAdmintask> entitystorematerialised_LocalCofAdmintask { get; set; }
        public virtual DbSet<entitystore_LocalCofAdmintask1> entitystore_LocalCofAdmintask1 { get; set; }
        public virtual DbSet<entitystore_LocalCofAdmintaskhistory> entitystore_LocalCofAdmintaskhistory { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofAdmintaskhistory1> entitystorematerialised_LocalCofAdmintaskhistory1 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofAppointment> entitystorematerialised_LocalCofAppointment { get; set; }
        public virtual DbSet<entitystore_LocalCofAppointment1> entitystore_LocalCofAppointment1 { get; set; }
        public virtual DbSet<entitystore_LocalCofAttendancestatus> entitystore_LocalCofAttendancestatus { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofAttendancestatus1> entitystorematerialised_LocalCofAttendancestatus1 { get; set; }
        public virtual DbSet<entitystore_LocalCofHl7messaging> entitystore_LocalCofHl7messaging { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofHl7messaging1> entitystorematerialised_LocalCofHl7messaging1 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupappointmentassignedto> entitystorematerialised_LocalCofLookupappointmentassignedto { get; set; }
        public virtual DbSet<entitystore_LocalCofLookupappointmentassignedto1> entitystore_LocalCofLookupappointmentassignedto1 { get; set; }
        public virtual DbSet<entitystore_LocalCofLookupappointmentattendstatus> entitystore_LocalCofLookupappointmentattendstatus { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupappointmentattendstatus1> entitystorematerialised_LocalCofLookupappointmentattendstatus1 { get; set; }
        public virtual DbSet<entitystore_LocalCofLookupappointmentpriority> entitystore_LocalCofLookupappointmentpriority { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupappointmentpriority1> entitystorematerialised_LocalCofLookupappointmentpriority1 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupappointmentreason> entitystorematerialised_LocalCofLookupappointmentreason { get; set; }
        public virtual DbSet<entitystore_LocalCofLookupappointmentreason1> entitystore_LocalCofLookupappointmentreason1 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupappointmentschedule> entitystorematerialised_LocalCofLookupappointmentschedule { get; set; }
        public virtual DbSet<entitystore_LocalCofLookupappointmentschedule1> entitystore_LocalCofLookupappointmentschedule1 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupappointmenttype> entitystorematerialised_LocalCofLookupappointmenttype { get; set; }
        public virtual DbSet<entitystore_LocalCofLookupappointmenttype1> entitystore_LocalCofLookupappointmenttype1 { get; set; }
        public virtual DbSet<entitystore_LocalCofLookupattendanceoutcome> entitystore_LocalCofLookupattendanceoutcome { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupattendanceoutcome1> entitystorematerialised_LocalCofLookupattendanceoutcome1 { get; set; }
        public virtual DbSet<entitystore_LocalCofLookupclinicoutcome> entitystore_LocalCofLookupclinicoutcome { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupclinicoutcome1> entitystorematerialised_LocalCofLookupclinicoutcome1 { get; set; }
        public virtual DbSet<entitystore_LocalCofLookupdecisiontotreatreason> entitystore_LocalCofLookupdecisiontotreatreason { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupdecisiontotreatreason1> entitystorematerialised_LocalCofLookupdecisiontotreatreason1 { get; set; }
        public virtual DbSet<entitystore_LocalCofLookupdischargereason> entitystore_LocalCofLookupdischargereason { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupdischargereason1> entitystorematerialised_LocalCofLookupdischargereason1 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupgeneral> entitystorematerialised_LocalCofLookupgeneral { get; set; }
        public virtual DbSet<entitystore_LocalCofLookupgeneral1> entitystore_LocalCofLookupgeneral1 { get; set; }
        public virtual DbSet<entitystore_LocalCofLookupinactivertt> entitystore_LocalCofLookupinactivertt { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupinactivertt1> entitystorematerialised_LocalCofLookupinactivertt1 { get; set; }
        public virtual DbSet<entitystore_LocalCofLookuplaterality> entitystore_LocalCofLookuplaterality { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookuplaterality1> entitystorematerialised_LocalCofLookuplaterality1 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupnextappointment> entitystorematerialised_LocalCofLookupnextappointment { get; set; }
        public virtual DbSet<entitystore_LocalCofLookupnextappointment1> entitystore_LocalCofLookupnextappointment1 { get; set; }
        public virtual DbSet<entitystore_LocalCofLookupprocedure> entitystore_LocalCofLookupprocedure { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupprocedure1> entitystorematerialised_LocalCofLookupprocedure1 { get; set; }
        public virtual DbSet<entitystore_LocalCofLookupriskdescription> entitystore_LocalCofLookupriskdescription { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupriskdescription1> entitystorematerialised_LocalCofLookupriskdescription1 { get; set; }
        public virtual DbSet<entitystore_LocalCofLookupriskflag> entitystore_LocalCofLookupriskflag { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupriskflag1> entitystorematerialised_LocalCofLookupriskflag1 { get; set; }
        public virtual DbSet<entitystore_LocalCofLookuprttpathwaytype> entitystore_LocalCofLookuprttpathwaytype { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookuprttpathwaytype1> entitystorematerialised_LocalCofLookuprttpathwaytype1 { get; set; }
        public virtual DbSet<entitystore_LocalCofLookupscheduleperriod> entitystore_LocalCofLookupscheduleperriod { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupscheduleperriod1> entitystorematerialised_LocalCofLookupscheduleperriod1 { get; set; }
        public virtual DbSet<entitystore_LocalCofLookupsite> entitystore_LocalCofLookupsite { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupsite1> entitystorematerialised_LocalCofLookupsite1 { get; set; }
        public virtual DbSet<entitystore_LocalCofLookupspecialty> entitystore_LocalCofLookupspecialty { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupspecialty1> entitystorematerialised_LocalCofLookupspecialty1 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookuptaskattendancemapping> entitystorematerialised_LocalCofLookuptaskattendancemapping { get; set; }
        public virtual DbSet<entitystore_LocalCofLookuptaskattendancemapping1> entitystore_LocalCofLookuptaskattendancemapping1 { get; set; }
        public virtual DbSet<entitystore_LocalCofPersonrisk> entitystore_LocalCofPersonrisk { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofPersonrisk1> entitystorematerialised_LocalCofPersonrisk1 { get; set; }
        public virtual DbSet<entitystore_LocalCofRecord> entitystore_LocalCofRecord { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofRecord1> entitystorematerialised_LocalCofRecord1 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofRttextract> entitystorematerialised_LocalCofRttextract { get; set; }
        public virtual DbSet<entitystore_LocalCofRttextract1> entitystore_LocalCofRttextract1 { get; set; }
        public virtual DbSet<entitystore_LocalCofSubtype> entitystore_LocalCofSubtype { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofSubtype1> entitystorematerialised_LocalCofSubtype1 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofSystemattributes> entitystorematerialised_LocalCofSystemattributes { get; set; }
        public virtual DbSet<entitystore_LocalCofSystemattributes1> entitystore_LocalCofSystemattributes1 { get; set; }
        public virtual DbSet<entitystore_LocalCofTreatment> entitystore_LocalCofTreatment { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofTreatment1> entitystorematerialised_LocalCofTreatment1 { get; set; }
        public virtual DbSet<entitystore_LocalCofWaynetest> entitystore_LocalCofWaynetest { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofWaynetest1> entitystorematerialised_LocalCofWaynetest1 { get; set; }
        public virtual DbSet<entitystore_LocalDemo1Exportentity1111> entitystore_LocalDemo1Exportentity1111 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemo1Exportentity11111> entitystorematerialised_LocalDemo1Exportentity11111 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemo1Exportentity2222> entitystorematerialised_LocalDemo1Exportentity2222 { get; set; }
        public virtual DbSet<entitystore_LocalDemo1Exportentity22221> entitystore_LocalDemo1Exportentity22221 { get; set; }
        public virtual DbSet<entitystore_LocalDemo1Exportentity3333> entitystore_LocalDemo1Exportentity3333 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemo1Exportentity33331> entitystorematerialised_LocalDemo1Exportentity33331 { get; set; }
        public virtual DbSet<entitystore_LocalDemo1Exportentity4444> entitystore_LocalDemo1Exportentity4444 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemo1Exportentity44441> entitystorematerialised_LocalDemo1Exportentity44441 { get; set; }
        public virtual DbSet<entitystore_LocalDemo1Exportentity6666> entitystore_LocalDemo1Exportentity6666 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemo1Exportentity66661> entitystorematerialised_LocalDemo1Exportentity66661 { get; set; }
        public virtual DbSet<entitystore_LocalDemo1Newsampletoday> entitystore_LocalDemo1Newsampletoday { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemo1Newsampletoday1> entitystorematerialised_LocalDemo1Newsampletoday1 { get; set; }
        public virtual DbSet<entitystore_LocalDemoAa> entitystore_LocalDemoAa { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoAa1> entitystorematerialised_LocalDemoAa1 { get; set; }
        public virtual DbSet<entitystore_LocalDemoBedboard> entitystore_LocalDemoBedboard { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoBedboard1> entitystorematerialised_LocalDemoBedboard1 { get; set; }
        public virtual DbSet<entitystore_LocalDemoBi> entitystore_LocalDemoBi { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoBi1> entitystorematerialised_LocalDemoBi1 { get; set; }
        public virtual DbSet<entitystore_LocalDemoBloodpressure> entitystore_LocalDemoBloodpressure { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoBloodpressure1> entitystorematerialised_LocalDemoBloodpressure1 { get; set; }
        public virtual DbSet<entitystore_LocalDemoBmitest> entitystore_LocalDemoBmitest { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoBmitest1> entitystorematerialised_LocalDemoBmitest1 { get; set; }
        public virtual DbSet<entitystore_LocalDemoIndiwardemo> entitystore_LocalDemoIndiwardemo { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoIndiwardemo1> entitystorematerialised_LocalDemoIndiwardemo1 { get; set; }
        public virtual DbSet<entitystore_LocalDemoInfectiontimeline> entitystore_LocalDemoInfectiontimeline { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoInfectiontimeline1> entitystorematerialised_LocalDemoInfectiontimeline1 { get; set; }
        public virtual DbSet<entitystore_LocalDemoRahul> entitystore_LocalDemoRahul { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoRahul1> entitystorematerialised_LocalDemoRahul1 { get; set; }
        public virtual DbSet<entitystore_LocalDemoRelationtest> entitystore_LocalDemoRelationtest { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoRelationtest1> entitystorematerialised_LocalDemoRelationtest1 { get; set; }
        public virtual DbSet<entitystore_LocalDemoRktestentity> entitystore_LocalDemoRktestentity { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoRktestentity1> entitystorematerialised_LocalDemoRktestentity1 { get; set; }
        public virtual DbSet<entitystore_LocalDemoSachindemo> entitystore_LocalDemoSachindemo { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoSachindemo1> entitystorematerialised_LocalDemoSachindemo1 { get; set; }
        public virtual DbSet<entitystore_LocalDemoSalford> entitystore_LocalDemoSalford { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoSalford1> entitystorematerialised_LocalDemoSalford1 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoSample> entitystorematerialised_LocalDemoSample { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoSampleentity1> entitystorematerialised_LocalDemoSampleentity1 { get; set; }
        public virtual DbSet<entitystore_LocalDemoSampleentity11> entitystore_LocalDemoSampleentity11 { get; set; }
        public virtual DbSet<entitystore_LocalDemoTest> entitystore_LocalDemoTest { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoTest1> entitystorematerialised_LocalDemoTest1 { get; set; }
        public virtual DbSet<entitystore_LocalEboardsEncounter> entitystore_LocalEboardsEncounter { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEboardsEncounter1> entitystorematerialised_LocalEboardsEncounter1 { get; set; }
        public virtual DbSet<entitystore_LocalEboardsWardinformation> entitystore_LocalEboardsWardinformation { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEboardsWardinformation1> entitystorematerialised_LocalEboardsWardinformation1 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalLookupSpecialty> entitystorematerialised_LocalLookupSpecialty { get; set; }
        public virtual DbSet<entitystore_LocalLookupSpecialty1> entitystore_LocalLookupSpecialty1 { get; set; }
        public virtual DbSet<entitystore_LocalRnohIntendedprocedure> entitystore_LocalRnohIntendedprocedure { get; set; }
        public virtual DbSet<entitystorematerialised_LocalRnohIntendedprocedure1> entitystorematerialised_LocalRnohIntendedprocedure1 { get; set; }
        public virtual DbSet<entitystore_LocalRtsComment> entitystore_LocalRtsComment { get; set; }
        public virtual DbSet<entitystorematerialised_LocalRtsComment1> entitystorematerialised_LocalRtsComment1 { get; set; }
        public virtual DbSet<entitystore_LocalRtsDocument> entitystore_LocalRtsDocument { get; set; }
        public virtual DbSet<entitystorematerialised_LocalRtsDocument1> entitystorematerialised_LocalRtsDocument1 { get; set; }
        public virtual DbSet<entitystore_LocalRtsReferencedata> entitystore_LocalRtsReferencedata { get; set; }
        public virtual DbSet<entitystorematerialised_LocalRtsReferencedata1> entitystorematerialised_LocalRtsReferencedata1 { get; set; }
        public virtual DbSet<entitystore_LocalRtsReferral> entitystore_LocalRtsReferral { get; set; }
        public virtual DbSet<entitystorematerialised_LocalRtsReferral1> entitystorematerialised_LocalRtsReferral1 { get; set; }
        public virtual DbSet<entitystore_LocalSecambCad> entitystore_LocalSecambCad { get; set; }
        public virtual DbSet<entitystorematerialised_LocalSecambCad1> entitystorematerialised_LocalSecambCad1 { get; set; }
        public virtual DbSet<entitystore_LocalSecambEpcr> entitystore_LocalSecambEpcr { get; set; }
        public virtual DbSet<entitystorematerialised_LocalSecambEpcr1> entitystorematerialised_LocalSecambEpcr1 { get; set; }
        public virtual DbSet<entitystore_LocalSecambEpcramended> entitystore_LocalSecambEpcramended { get; set; }
        public virtual DbSet<entitystorematerialised_LocalSecambEpcramended1> entitystorematerialised_LocalSecambEpcramended1 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalTerminusForm> entitystorematerialised_LocalTerminusForm { get; set; }
        public virtual DbSet<entitystore_LocalTerminusForm1> entitystore_LocalTerminusForm1 { get; set; }
        public virtual DbSet<entitystore_LocalTerminusFormfield> entitystore_LocalTerminusFormfield { get; set; }
        public virtual DbSet<entitystorematerialised_LocalTerminusFormfield1> entitystorematerialised_LocalTerminusFormfield1 { get; set; }
        public virtual DbSet<entitystore_LocalTerminusFormsection> entitystore_LocalTerminusFormsection { get; set; }
        public virtual DbSet<entitystorematerialised_LocalTerminusFormsection1> entitystorematerialised_LocalTerminusFormsection1 { get; set; }
        public virtual DbSet<entitystore_LocalTerminusMedicaltest> entitystore_LocalTerminusMedicaltest { get; set; }
        public virtual DbSet<entitystorematerialised_LocalTerminusMedicaltest1> entitystorematerialised_LocalTerminusMedicaltest1 { get; set; }
        public virtual DbSet<entitystore_LocalTerminusSpvlog> entitystore_LocalTerminusSpvlog { get; set; }
        public virtual DbSet<entitystorematerialised_LocalTerminusSpvlog1> entitystorematerialised_LocalTerminusSpvlog1 { get; set; }
        public virtual DbSet<entitystore_LocalUszDemoperson> entitystore_LocalUszDemoperson { get; set; }
        public virtual DbSet<entitystorematerialised_LocalUszDemoperson1> entitystorematerialised_LocalUszDemoperson1 { get; set; }
        public virtual DbSet<entitystore_MasterAccountmerges> entitystore_MasterAccountmerges { get; set; }
        public virtual DbSet<entitystorematerialised_MasterAccountmerges1> entitystorematerialised_MasterAccountmerges1 { get; set; }
        public virtual DbSet<entitystore_MasterEncounter> entitystore_MasterEncounter { get; set; }
        public virtual DbSet<entitystorematerialised_MasterEncounter1> entitystorematerialised_MasterEncounter1 { get; set; }
        public virtual DbSet<entitystore_MasterEncountermerges> entitystore_MasterEncountermerges { get; set; }
        public virtual DbSet<entitystorematerialised_MasterEncountermerges1> entitystorematerialised_MasterEncountermerges1 { get; set; }
        public virtual DbSet<entitystore_MasterPerson> entitystore_MasterPerson { get; set; }
        public virtual DbSet<entitystorematerialised_MasterPerson1> entitystorematerialised_MasterPerson1 { get; set; }
        public virtual DbSet<entitystore_MasterPersonmerges> entitystore_MasterPersonmerges { get; set; }
        public virtual DbSet<entitystorematerialised_MasterPersonmerges1> entitystorematerialised_MasterPersonmerges1 { get; set; }
        public virtual DbSet<entitystore_MasterTestentity> entitystore_MasterTestentity { get; set; }
        public virtual DbSet<entitystorematerialised_MasterTestentity1> entitystorematerialised_MasterTestentity1 { get; set; }
        public virtual DbSet<entitystore_MetaAdminpins> entitystore_MetaAdminpins { get; set; }
        public virtual DbSet<entitystorematerialised_MetaAdminpins1> entitystorematerialised_MetaAdminpins1 { get; set; }
        public virtual DbSet<entitystore_MetaApplication> entitystore_MetaApplication { get; set; }
        public virtual DbSet<entitystorematerialised_MetaApplication1> entitystorematerialised_MetaApplication1 { get; set; }
        public virtual DbSet<entitystore_MetaApplicationlist> entitystore_MetaApplicationlist { get; set; }
        public virtual DbSet<entitystorematerialised_MetaApplicationlist1> entitystorematerialised_MetaApplicationlist1 { get; set; }
        public virtual DbSet<entitystore_MetaApplicationmodulemapping> entitystore_MetaApplicationmodulemapping { get; set; }
        public virtual DbSet<entitystorematerialised_MetaApplicationmodulemapping1> entitystorematerialised_MetaApplicationmodulemapping1 { get; set; }
        public virtual DbSet<entitystore_MetaBedstatus> entitystore_MetaBedstatus { get; set; }
        public virtual DbSet<entitystorematerialised_MetaBedstatus1> entitystorematerialised_MetaBedstatus1 { get; set; }
        public virtual DbSet<entitystore_MetaCarerecordtype> entitystore_MetaCarerecordtype { get; set; }
        public virtual DbSet<entitystorematerialised_MetaCarerecordtype1> entitystorematerialised_MetaCarerecordtype1 { get; set; }
        public virtual DbSet<entitystore_MetaChart> entitystore_MetaChart { get; set; }
        public virtual DbSet<entitystorematerialised_MetaChart1> entitystorematerialised_MetaChart1 { get; set; }
        public virtual DbSet<entitystore_MetaChartgraph> entitystore_MetaChartgraph { get; set; }
        public virtual DbSet<entitystorematerialised_MetaChartgraph1> entitystorematerialised_MetaChartgraph1 { get; set; }
        public virtual DbSet<baseview_MetaCliniccontext> baseview_MetaCliniccontext { get; set; }
        public virtual DbSet<baseview_MetaConsultantcontext> baseview_MetaConsultantcontext { get; set; }
        public virtual DbSet<baseview_MetaFluidbalanceintakeroute> baseview_MetaFluidbalanceintakeroute { get; set; }
        public virtual DbSet<baseview_MetaFluidbalanceoutputroute> baseview_MetaFluidbalanceoutputroute { get; set; }
        public virtual DbSet<entitystore_MetaFluidbalanceroute> entitystore_MetaFluidbalanceroute { get; set; }
        public virtual DbSet<entitystorematerialised_MetaFluidbalanceroute1> entitystorematerialised_MetaFluidbalanceroute1 { get; set; }
        public virtual DbSet<entitystore_MetaFluidbalancetimeslot> entitystore_MetaFluidbalancetimeslot { get; set; }
        public virtual DbSet<entitystorematerialised_MetaFluidbalancetimeslot1> entitystorematerialised_MetaFluidbalancetimeslot1 { get; set; }
        public virtual DbSet<entitystore_MetaFluidbalancetype> entitystore_MetaFluidbalancetype { get; set; }
        public virtual DbSet<entitystorematerialised_MetaFluidbalancetype1> entitystorematerialised_MetaFluidbalancetype1 { get; set; }
        public virtual DbSet<entitystore_MetaGraph> entitystore_MetaGraph { get; set; }
        public virtual DbSet<entitystorematerialised_MetaGraph1> entitystorematerialised_MetaGraph1 { get; set; }
        public virtual DbSet<entitystore_MetaGraphband> entitystore_MetaGraphband { get; set; }
        public virtual DbSet<entitystorematerialised_MetaGraphband1> entitystorematerialised_MetaGraphband1 { get; set; }
        public virtual DbSet<baseview_MetaGraphcharts> baseview_MetaGraphcharts { get; set; }
        public virtual DbSet<entitystore_MetaGraphparameterkey> entitystore_MetaGraphparameterkey { get; set; }
        public virtual DbSet<entitystorematerialised_MetaGraphparameterkey1> entitystorematerialised_MetaGraphparameterkey1 { get; set; }
        public virtual DbSet<entitystore_MetaGraphscale> entitystore_MetaGraphscale { get; set; }
        public virtual DbSet<entitystorematerialised_MetaGraphscale1> entitystorematerialised_MetaGraphscale1 { get; set; }
        public virtual DbSet<entitystore_MetaListcontexts> entitystore_MetaListcontexts { get; set; }
        public virtual DbSet<entitystorematerialised_MetaListcontexts1> entitystorematerialised_MetaListcontexts1 { get; set; }
        public virtual DbSet<entitystore_MetaModule> entitystore_MetaModule { get; set; }
        public virtual DbSet<entitystorematerialised_MetaModule1> entitystorematerialised_MetaModule1 { get; set; }
        public virtual DbSet<baseview_MetaModulelist> baseview_MetaModulelist { get; set; }
        public virtual DbSet<entitystore_MetaObservationchartsettings> entitystore_MetaObservationchartsettings { get; set; }
        public virtual DbSet<entitystorematerialised_MetaObservationchartsettings1> entitystorematerialised_MetaObservationchartsettings1 { get; set; }
        public virtual DbSet<entitystore_MetaObservationscaletype> entitystore_MetaObservationscaletype { get; set; }
        public virtual DbSet<entitystorematerialised_MetaObservationscaletype1> entitystorematerialised_MetaObservationscaletype1 { get; set; }
        public virtual DbSet<entitystore_MetaObservationtype> entitystore_MetaObservationtype { get; set; }
        public virtual DbSet<entitystorematerialised_MetaObservationtype1> entitystorematerialised_MetaObservationtype1 { get; set; }
        public virtual DbSet<entitystore_MetaObservationtypemeasurement> entitystore_MetaObservationtypemeasurement { get; set; }
        public virtual DbSet<entitystorematerialised_MetaObservationtypemeasurement1> entitystorematerialised_MetaObservationtypemeasurement1 { get; set; }
        public virtual DbSet<entitystore_MetaOxygendevices> entitystore_MetaOxygendevices { get; set; }
        public virtual DbSet<entitystorematerialised_MetaOxygendevices1> entitystorematerialised_MetaOxygendevices1 { get; set; }
        public virtual DbSet<entitystore_MetaPersona> entitystore_MetaPersona { get; set; }
        public virtual DbSet<entitystorematerialised_MetaPersona1> entitystorematerialised_MetaPersona1 { get; set; }
        public virtual DbSet<baseview_MetaPersona2> baseview_MetaPersona2 { get; set; }
        public virtual DbSet<entitystore_MetaPersonacontext> entitystore_MetaPersonacontext { get; set; }
        public virtual DbSet<entitystorematerialised_MetaPersonacontext1> entitystorematerialised_MetaPersonacontext1 { get; set; }
        public virtual DbSet<entitystore_MetaPersonacontextgroup> entitystore_MetaPersonacontextgroup { get; set; }
        public virtual DbSet<entitystorematerialised_MetaPersonacontextgroup1> entitystorematerialised_MetaPersonacontextgroup1 { get; set; }
        public virtual DbSet<entitystore_MetaPersonacontextgroupusers> entitystore_MetaPersonacontextgroupusers { get; set; }
        public virtual DbSet<entitystorematerialised_MetaPersonacontextgroupusers1> entitystorematerialised_MetaPersonacontextgroupusers1 { get; set; }
        public virtual DbSet<entitystore_MetaPersonacontextmappingcodes> entitystore_MetaPersonacontextmappingcodes { get; set; }
        public virtual DbSet<entitystorematerialised_MetaPersonacontextmappingcodes1> entitystorematerialised_MetaPersonacontextmappingcodes1 { get; set; }
        public virtual DbSet<baseview_MetaTheatrecontext> baseview_MetaTheatrecontext { get; set; }
        public virtual DbSet<entitystore_MetaWard> entitystore_MetaWard { get; set; }
        public virtual DbSet<entitystorematerialised_MetaWard1> entitystorematerialised_MetaWard1 { get; set; }
        public virtual DbSet<entitystorematerialised_MetaWardbay> entitystorematerialised_MetaWardbay { get; set; }
        public virtual DbSet<entitystore_MetaWardbay1> entitystore_MetaWardbay1 { get; set; }
        public virtual DbSet<entitystore_MetaWardbaybed> entitystore_MetaWardbaybed { get; set; }
        public virtual DbSet<entitystorematerialised_MetaWardbaybed1> entitystorematerialised_MetaWardbaybed1 { get; set; }
        public virtual DbSet<entitystore_MetaWardwithoutbed> entitystore_MetaWardwithoutbed { get; set; }
        public virtual DbSet<entitystorematerialised_MetaWardwithoutbed1> entitystorematerialised_MetaWardwithoutbed1 { get; set; }
        public virtual DbSet<entitystore_MetaWarningscoresystem> entitystore_MetaWarningscoresystem { get; set; }
        public virtual DbSet<entitystorematerialised_MetaWarningscoresystem1> entitystorematerialised_MetaWarningscoresystem1 { get; set; }
        public virtual DbSet<baseview_NhsersGetersworklist> baseview_NhsersGetersworklist { get; set; }
        public virtual DbSet<baseview_PatientbannerColumn2> baseview_PatientbannerColumn2 { get; set; }
        public virtual DbSet<baseview_PatientbannerLatestipencounter> baseview_PatientbannerLatestipencounter { get; set; }
        public virtual DbSet<baseview_PatientbannerMainbanner> baseview_PatientbannerMainbanner { get; set; }
        public virtual DbSet<baseview_PatientbannerPersonaddress> baseview_PatientbannerPersonaddress { get; set; }
        public virtual DbSet<baseview_PatientbannerPersonallergy> baseview_PatientbannerPersonallergy { get; set; }
        public virtual DbSet<baseview_PatientbannerPersoncontactinfo> baseview_PatientbannerPersoncontactinfo { get; set; }
        public virtual DbSet<baseview_PatientbannerPersonidentifier> baseview_PatientbannerPersonidentifier { get; set; }
        public virtual DbSet<baseview_PatientbannerPersoninfo> baseview_PatientbannerPersoninfo { get; set; }
        public virtual DbSet<baseview_PatientbannerPersonobservation> baseview_PatientbannerPersonobservation { get; set; }
        public virtual DbSet<baseview_PoaAsa1worklist> baseview_PoaAsa1worklist { get; set; }
        public virtual DbSet<baseview_RtsComments> baseview_RtsComments { get; set; }
        public virtual DbSet<baseview_RtsWorklist> baseview_RtsWorklist { get; set; }
        public virtual DbSet<baseview_SecambCad> baseview_SecambCad { get; set; }
        public virtual DbSet<baseview_SecambCadswithoutpcr> baseview_SecambCadswithoutpcr { get; set; }
        public virtual DbSet<baseview_SecambEpcr> baseview_SecambEpcr { get; set; }
        public virtual DbSet<baseview_SecambNoncompliantresponse> baseview_SecambNoncompliantresponse { get; set; }
        public virtual DbSet<baseview_SecambRandomresponse> baseview_SecambRandomresponse { get; set; }
        public virtual DbSet<baseview_SecambStemi> baseview_SecambStemi { get; set; }
        public virtual DbSet<baseview_TerminusAllinpatients> baseview_TerminusAllinpatients { get; set; }
        public virtual DbSet<baseview_TerminusAllinpatientswithhighews> baseview_TerminusAllinpatientswithhighews { get; set; }
        public virtual DbSet<baseview_TerminusAllpatientswithobservationsdueoroverdue> baseview_TerminusAllpatientswithobservationsdueoroverdue { get; set; }
        public virtual DbSet<baseview_TerminusFluidbalancechart> baseview_TerminusFluidbalancechart { get; set; }
        public virtual DbSet<baseview_TerminusMycurrentinpatients> baseview_TerminusMycurrentinpatients { get; set; }
        public virtual DbSet<entitystore_TerminusMypatients> entitystore_TerminusMypatients { get; set; }
        public virtual DbSet<entitystorematerialised_TerminusMypatients1> entitystorematerialised_TerminusMypatients1 { get; set; }
        public virtual DbSet<baseview_TerminusPatientbanner> baseview_TerminusPatientbanner { get; set; }
        public virtual DbSet<entitystore_TerminusPatientlist> entitystore_TerminusPatientlist { get; set; }
        public virtual DbSet<entitystorematerialised_TerminusPatientlist1> entitystorematerialised_TerminusPatientlist1 { get; set; }
        public virtual DbSet<baseview_TerminusPatientlist2> baseview_TerminusPatientlist2 { get; set; }
        public virtual DbSet<baseview_TerminusPatientlists> baseview_TerminusPatientlists { get; set; }
        public virtual DbSet<baseview_TerminusPatientsearch> baseview_TerminusPatientsearch { get; set; }
        public virtual DbSet<entitystore_TerminusPersonpatientlist> entitystore_TerminusPersonpatientlist { get; set; }
        public virtual DbSet<entitystorematerialised_TerminusPersonpatientlist1> entitystorematerialised_TerminusPersonpatientlist1 { get; set; }
        public virtual DbSet<baseview_TerminusPersonswithids> baseview_TerminusPersonswithids { get; set; }
        public virtual DbSet<baseview_TerminusSpvobservations> baseview_TerminusSpvobservations { get; set; }
        public virtual DbSet<baseview_TerminusSpvobservationsbyevent> baseview_TerminusSpvobservationsbyevent { get; set; }
        public virtual DbSet<baseview_TerminusSpvobservationsbyeventchart> baseview_TerminusSpvobservationsbyeventchart { get; set; }
        public virtual DbSet<baseview_TestDemobmitest> baseview_TestDemobmitest { get; set; }
        public virtual DbSet<baseview_TestJsont> baseview_TestJsont { get; set; }
        public virtual DbSet<baseview_TestObshcart3> baseview_TestObshcart3 { get; set; }
        public virtual DbSet<baseview_TestTest> baseview_TestTest { get; set; }
        public virtual DbSet<baseview_TestTestgs> baseview_TestTestgs { get; set; }

    }
}
