//Interneuron Synapse

//Copyright(C) 2021  Interneuron CIC

//This program is free software: you can redistribute it and/or modify
//it under the terms of the GNU General Public License as published by
//the Free Software Foundation, either version 3 of the License, or
//(at your option) any later version.

//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

//See the
//GNU General Public License for more details.

//You should have received a copy of the GNU General Public License
//along with this program.If not, see<http://www.gnu.org/licenses/>.


﻿using System;
using Microsoft.EntityFrameworkCore;
using Interneuron.CareRecord.Model.DomainModels;
using Microsoft.EntityFrameworkCore.Metadata;
using Interneuron.CareRecord.Repository;
using Microsoft.Extensions.Configuration;

namespace Interneuron.CareRecord.Repository.DBModelsContext
{
    public partial class SynapseDBContext
    {
        public virtual DbSet<baseview_AneAne> baseview_AneAne { get; set; }
        public virtual DbSet<baseview_AneAnegreaterthan4hours> baseview_AneAnegreaterthan4hours { get; set; }
        public virtual DbSet<baseview_AneRecentlydischarged> baseview_AneRecentlydischarged { get; set; }
        public virtual DbSet<baseview_AutonomicObservationevent> baseview_AutonomicObservationevent { get; set; }
        public virtual DbSet<baseview_BvCoreAlloperation> baseview_BvCoreAlloperation { get; set; }
        public virtual DbSet<baseview_BvCoreAssessments> baseview_BvCoreAssessments { get; set; }
        public virtual DbSet<baseview_BvCoreClinicalsummary> baseview_BvCoreClinicalsummary { get; set; }
        public virtual DbSet<baseview_BvCoreImplantdata> baseview_BvCoreImplantdata { get; set; }
        public virtual DbSet<baseview_BvCoreInpatientappointments> baseview_BvCoreInpatientappointments { get; set; }
        public virtual DbSet<baseview_BvCoreInpatientencountersforfluidbalance> baseview_BvCoreInpatientencountersforfluidbalance { get; set; }
        public virtual DbSet<baseview_BvCoreMaxlastviewedorderaudit> baseview_BvCoreMaxlastviewedorderaudit { get; set; }
        public virtual DbSet<baseview_BvCoreOperationdetail> baseview_BvCoreOperationdetail { get; set; }
        public virtual DbSet<baseview_BvCoreOperationdiagnosis> baseview_BvCoreOperationdiagnosis { get; set; }
        public virtual DbSet<baseview_BvCoreOperationjson> baseview_BvCoreOperationjson { get; set; }
        public virtual DbSet<baseview_BvCoreOperationlist> baseview_BvCoreOperationlist { get; set; }
        public virtual DbSet<baseview_BvCoreOperationnotehistory> baseview_BvCoreOperationnotehistory { get; set; }
        public virtual DbSet<baseview_BvCoreOperationnotepatientbanner> baseview_BvCoreOperationnotepatientbanner { get; set; }
        public virtual DbSet<baseview_BvCoreOperationnotepdf> baseview_BvCoreOperationnotepdf { get; set; }
        public virtual DbSet<baseview_BvCoreOperationnotepdfhistory> baseview_BvCoreOperationnotepdfhistory { get; set; }
        public virtual DbSet<baseview_BvCoreOperationprocedure> baseview_BvCoreOperationprocedure { get; set; }
        public virtual DbSet<baseview_BvCoreOperationprovider> baseview_BvCoreOperationprovider { get; set; }
        public virtual DbSet<baseview_BvCoreOrdercategory> baseview_BvCoreOrdercategory { get; set; }
        public virtual DbSet<baseview_BvCoreOrdernote> baseview_BvCoreOrdernote { get; set; }
        public virtual DbSet<baseview_BvCoreOrderresult> baseview_BvCoreOrderresult { get; set; }
        public virtual DbSet<baseview_BvCorePersonorder> baseview_BvCorePersonorder { get; set; }
        public virtual DbSet<baseview_BvCorePersonordercount> baseview_BvCorePersonordercount { get; set; }
        public virtual DbSet<baseview_BvCoreProcedureprovider> baseview_BvCoreProcedureprovider { get; set; }
        public virtual DbSet<baseview_BvCoreTomorrowsoperation> baseview_BvCoreTomorrowsoperation { get; set; }
        public virtual DbSet<baseview_BvCoreYesterdaysoperation> baseview_BvCoreYesterdaysoperation { get; set; }
        public virtual DbSet<baseview_BvassessmentAllassessmentdetails> baseview_BvassessmentAllassessmentdetails { get; set; }
        public virtual DbSet<baseview_BvassessmentAllassessments> baseview_BvassessmentAllassessments { get; set; }
        public virtual DbSet<baseview_BvassessmentAllassessmentwithredandamber> baseview_BvassessmentAllassessmentwithredandamber { get; set; }
        public virtual DbSet<baseview_BvassessmentAlllatestassessmentdetails> baseview_BvassessmentAlllatestassessmentdetails { get; set; }
        public virtual DbSet<baseview_BvassessmentAlllatestassessments> baseview_BvassessmentAlllatestassessments { get; set; }
        public virtual DbSet<baseview_BvassessmentAlllatestassessmentstasks> baseview_BvassessmentAlllatestassessmentstasks { get; set; }
        public virtual DbSet<baseview_BvassessmentAlltopversionassessments> baseview_BvassessmentAlltopversionassessments { get; set; }
        public virtual DbSet<baseview_BvassessmentAlltopversionassessmentswithtaskcount> baseview_BvassessmentAlltopversionassessmentswithtaskcount { get; set; }
        public virtual DbSet<baseview_BvassessmentLatestbmi> baseview_BvassessmentLatestbmi { get; set; }
        public virtual DbSet<baseview_BvassessmentLatestcancerrecord> baseview_BvassessmentLatestcancerrecord { get; set; }
        public virtual DbSet<baseview_BvassessmentLatestplateletcount> baseview_BvassessmentLatestplateletcount { get; set; }
        public virtual DbSet<baseview_BvassessmentLatestvtehistory> baseview_BvassessmentLatestvtehistory { get; set; }
        public virtual DbSet<baseview_BvassessmentRedandamberreadjson> baseview_BvassessmentRedandamberreadjson { get; set; }
        public virtual DbSet<baseview_BvassessmentResultcodemapping> baseview_BvassessmentResultcodemapping { get; set; }
        public virtual DbSet<baseview_CarerecordDemographics> baseview_CarerecordDemographics { get; set; }
        public virtual DbSet<baseview_CarerecordObservations> baseview_CarerecordObservations { get; set; }
        public virtual DbSet<baseview_CarerecordResults> baseview_CarerecordResults { get; set; }
        public virtual DbSet<baseview_ClinicalsummaryClinicalsummarylist> baseview_ClinicalsummaryClinicalsummarylist { get; set; }
        public virtual DbSet<baseview_ClinicalsummaryClinicalsummarynotes> baseview_ClinicalsummaryClinicalsummarynotes { get; set; }
        public virtual DbSet<baseview_ClinicalsummaryClinicalsummarystatuses> baseview_ClinicalsummaryClinicalsummarystatuses { get; set; }
        public virtual DbSet<baseview_ClinicalsummaryCurrentinpatients> baseview_ClinicalsummaryCurrentinpatients { get; set; }
        public virtual DbSet<baseview_ClinicalsummaryDischargeplan> baseview_ClinicalsummaryDischargeplan { get; set; }
        public virtual DbSet<baseview_ClinicalsummaryGetdiagnoses> baseview_ClinicalsummaryGetdiagnoses { get; set; }
        public virtual DbSet<baseview_ClinicalsummaryGetlatestencounter> baseview_ClinicalsummaryGetlatestencounter { get; set; }
        public virtual DbSet<baseview_ClinicalsummaryGetprocedures> baseview_ClinicalsummaryGetprocedures { get; set; }
        public virtual DbSet<baseview_ClinicalsummaryGettasks> baseview_ClinicalsummaryGettasks { get; set; }
        public virtual DbSet<baseview_ClinicalsummaryInvestigation> baseview_ClinicalsummaryInvestigation { get; set; }
        public virtual DbSet<baseview_ClinicalsummaryLabresults> baseview_ClinicalsummaryLabresults { get; set; }
        public virtual DbSet<baseview_ClinicalsummaryLatestcrpresult> baseview_ClinicalsummaryLatestcrpresult { get; set; }
        public virtual DbSet<baseview_ClinicalsummaryLatestheartrateandtemperature> baseview_ClinicalsummaryLatestheartrateandtemperature { get; set; }
        public virtual DbSet<baseview_ClinicalsummaryLatestmicrobiologyreport> baseview_ClinicalsummaryLatestmicrobiologyreport { get; set; }
        public virtual DbSet<baseview_ClinicalsummaryTasklist> baseview_ClinicalsummaryTasklist { get; set; }
        public virtual DbSet<baseview_CofAppointmentswithlookups> baseview_CofAppointmentswithlookups { get; set; }
        public virtual DbSet<entitystorematerialised_CoreAdministermedication> entitystorematerialised_CoreAdministermedication { get; set; }
        public virtual DbSet<entitystorematerialised_CoreAdministermedicationcodes> entitystorematerialised_CoreAdministermedicationcodes { get; set; }
        public virtual DbSet<entitystorematerialised_CoreAdministermedicationingredients> entitystorematerialised_CoreAdministermedicationingredients { get; set; }
        public virtual DbSet<entitystorematerialised_CoreAllergyintolerance> entitystorematerialised_CoreAllergyintolerance { get; set; }
        public virtual DbSet<entitystorematerialised_CoreAssessment> entitystorematerialised_CoreAssessment { get; set; }
        public virtual DbSet<entitystorematerialised_CoreAssessmentdetail> entitystorematerialised_CoreAssessmentdetail { get; set; }
        public virtual DbSet<entitystorematerialised_CoreAssessmenttask> entitystorematerialised_CoreAssessmenttask { get; set; }
        public virtual DbSet<entitystorematerialised_CoreCarerecord> entitystorematerialised_CoreCarerecord { get; set; }
        public virtual DbSet<entitystorematerialised_CoreClinicalsummary> entitystorematerialised_CoreClinicalsummary { get; set; }
        public virtual DbSet<entitystorematerialised_CoreClinicalsummarynotes> entitystorematerialised_CoreClinicalsummarynotes { get; set; }
        public virtual DbSet<entitystorematerialised_CoreContinuousinfusion> entitystorematerialised_CoreContinuousinfusion { get; set; }
        public virtual DbSet<entitystorematerialised_CoreContinuousinfusionevent> entitystorematerialised_CoreContinuousinfusionevent { get; set; }
        public virtual DbSet<entitystorematerialised_CoreContinuousinfusionfluidloss> entitystorematerialised_CoreContinuousinfusionfluidloss { get; set; }
        public virtual DbSet<entitystorematerialised_CoreContinuousinfusionvalidation> entitystorematerialised_CoreContinuousinfusionvalidation { get; set; }
        public virtual DbSet<entitystorematerialised_CoreDiagnosis> entitystorematerialised_CoreDiagnosis { get; set; }
        public virtual DbSet<entitystorematerialised_CoreDischargeplan> entitystorematerialised_CoreDischargeplan { get; set; }
        public virtual DbSet<entitystorematerialised_CoreDocuments> entitystorematerialised_CoreDocuments { get; set; }
        public virtual DbSet<entitystorematerialised_CoreDocumentsrepository> entitystorematerialised_CoreDocumentsrepository { get; set; }
        public virtual DbSet<entitystorematerialised_CoreDose> entitystorematerialised_CoreDose { get; set; }
        public virtual DbSet<entitystorematerialised_CoreDoseevents> entitystorematerialised_CoreDoseevents { get; set; }
        public virtual DbSet<entitystorematerialised_CoreEncounter> entitystorematerialised_CoreEncounter { get; set; }
        public virtual DbSet<entitystorematerialised_CoreFluidbalanceescalation> entitystorematerialised_CoreFluidbalanceescalation { get; set; }
        public virtual DbSet<entitystorematerialised_CoreFluidbalanceintakeoutput> entitystorematerialised_CoreFluidbalanceintakeoutput { get; set; }
        public virtual DbSet<entitystorematerialised_CoreFluidbalancepersonstatus> entitystorematerialised_CoreFluidbalancepersonstatus { get; set; }
        public virtual DbSet<entitystorematerialised_CoreFluidbalancesession> entitystorematerialised_CoreFluidbalancesession { get; set; }
        public virtual DbSet<entitystorematerialised_CoreFluidbalancesessionroute> entitystorematerialised_CoreFluidbalancesessionroute { get; set; }
        public virtual DbSet<entitystorematerialised_CoreFluidbalancesessionroutesessions> entitystorematerialised_CoreFluidbalancesessionroutesessions { get; set; }
        public virtual DbSet<entitystorematerialised_CoreFormbuilderresponse> entitystorematerialised_CoreFormbuilderresponse { get; set; }
        public virtual DbSet<entitystorematerialised_CoreImplantcomponent> entitystorematerialised_CoreImplantcomponent { get; set; }
        public virtual DbSet<entitystorematerialised_CoreImplantcomponentgroup> entitystorematerialised_CoreImplantcomponentgroup { get; set; }
        public virtual DbSet<entitystorematerialised_CoreImplantcomponentparameter> entitystorematerialised_CoreImplantcomponentparameter { get; set; }
        public virtual DbSet<entitystorematerialised_CoreImplantcomponentrule> entitystorematerialised_CoreImplantcomponentrule { get; set; }
        public virtual DbSet<entitystorematerialised_CoreImplantcomponentrule2> entitystorematerialised_CoreImplantcomponentrule2 { get; set; }
        public virtual DbSet<entitystorematerialised_CoreImplantmanufacturer> entitystorematerialised_CoreImplantmanufacturer { get; set; }
        public virtual DbSet<entitystorematerialised_CoreImplantsystem> entitystorematerialised_CoreImplantsystem { get; set; }
        public virtual DbSet<entitystorematerialised_CoreImplantsystemcomponent> entitystorematerialised_CoreImplantsystemcomponent { get; set; }
        public virtual DbSet<entitystorematerialised_CoreIndication> entitystorematerialised_CoreIndication { get; set; }
        public virtual DbSet<entitystorematerialised_CoreInfusionevents> entitystorematerialised_CoreInfusionevents { get; set; }
        public virtual DbSet<entitystorematerialised_CoreInstruction> entitystorematerialised_CoreInstruction { get; set; }
        public virtual DbSet<entitystorematerialised_CoreInvestigation> entitystorematerialised_CoreInvestigation { get; set; }
        public virtual DbSet<entitystorematerialised_CoreList> entitystorematerialised_CoreList { get; set; }
        public virtual DbSet<entitystorematerialised_CoreListquestion> entitystorematerialised_CoreListquestion { get; set; }
        public virtual DbSet<entitystorematerialised_CoreListquestionvalue> entitystorematerialised_CoreListquestionvalue { get; set; }
        public virtual DbSet<entitystorematerialised_CoreLocation> entitystorematerialised_CoreLocation { get; set; }
        public virtual DbSet<entitystorematerialised_CoreMedication> entitystorematerialised_CoreMedication { get; set; }
        public virtual DbSet<entitystorematerialised_CoreMedicationadministration> entitystorematerialised_CoreMedicationadministration { get; set; }
        public virtual DbSet<entitystorematerialised_CoreMedicationcodes> entitystorematerialised_CoreMedicationcodes { get; set; }
        public virtual DbSet<entitystorematerialised_CoreMedicationingredients> entitystorematerialised_CoreMedicationingredients { get; set; }
        public virtual DbSet<entitystorematerialised_CoreMedicationroutes> entitystorematerialised_CoreMedicationroutes { get; set; }
        public virtual DbSet<entitystorematerialised_CoreNextofkin> entitystorematerialised_CoreNextofkin { get; set; }
        public virtual DbSet<entitystorematerialised_CoreNote> entitystorematerialised_CoreNote { get; set; }
        public virtual DbSet<entitystorematerialised_CoreObservation> entitystorematerialised_CoreObservation { get; set; }
        public virtual DbSet<entitystorematerialised_CoreObservationevent> entitystorematerialised_CoreObservationevent { get; set; }
        public virtual DbSet<entitystorematerialised_CoreObservationeventmonitoring> entitystorematerialised_CoreObservationeventmonitoring { get; set; }
        public virtual DbSet<entitystorematerialised_CoreOperation> entitystorematerialised_CoreOperation { get; set; }
        public virtual DbSet<entitystorematerialised_CoreOperationanaesthetic> entitystorematerialised_CoreOperationanaesthetic { get; set; }
        public virtual DbSet<entitystorematerialised_CoreOperationantibiotics> entitystorematerialised_CoreOperationantibiotics { get; set; }
        public virtual DbSet<entitystorematerialised_CoreOperationnotehendersonoutcome> entitystorematerialised_CoreOperationnotehendersonoutcome { get; set; }
        public virtual DbSet<entitystorematerialised_CoreOperationnotehistory> entitystorematerialised_CoreOperationnotehistory { get; set; }
        public virtual DbSet<entitystorematerialised_CoreOperationpostopinstructions> entitystorematerialised_CoreOperationpostopinstructions { get; set; }
        public virtual DbSet<entitystorematerialised_CoreOperationpreparation> entitystorematerialised_CoreOperationpreparation { get; set; }
        public virtual DbSet<entitystorematerialised_CoreOperationprovider> entitystorematerialised_CoreOperationprovider { get; set; }
        public virtual DbSet<entitystorematerialised_CoreOperationspecialty> entitystorematerialised_CoreOperationspecialty { get; set; }
        public virtual DbSet<entitystorematerialised_CoreOrder> entitystorematerialised_CoreOrder { get; set; }
        public virtual DbSet<entitystorematerialised_CoreOrderaudit> entitystorematerialised_CoreOrderaudit { get; set; }
        public virtual DbSet<entitystorematerialised_CoreOrderset> entitystorematerialised_CoreOrderset { get; set; }
        public virtual DbSet<entitystorematerialised_CoreOrdersetprescription> entitystorematerialised_CoreOrdersetprescription { get; set; }
        public virtual DbSet<entitystorematerialised_CorePerson> entitystorematerialised_CorePerson { get; set; }
        public virtual DbSet<entitystorematerialised_CorePersonaddress> entitystorematerialised_CorePersonaddress { get; set; }
        public virtual DbSet<entitystorematerialised_CorePersonaddresstype> entitystorematerialised_CorePersonaddresstype { get; set; }
        public virtual DbSet<entitystorematerialised_CorePersoncontactinfo> entitystorematerialised_CorePersoncontactinfo { get; set; }
        public virtual DbSet<entitystorematerialised_CorePersonidentifier> entitystorematerialised_CorePersonidentifier { get; set; }
        public virtual DbSet<entitystorematerialised_CorePersonobservationscale> entitystorematerialised_CorePersonobservationscale { get; set; }
        public virtual DbSet<entitystorematerialised_CorePosology> entitystorematerialised_CorePosology { get; set; }
        public virtual DbSet<entitystorematerialised_CorePrescription> entitystorematerialised_CorePrescription { get; set; }
        public virtual DbSet<entitystorematerialised_CorePrescriptionorderset> entitystorematerialised_CorePrescriptionorderset { get; set; }
        public virtual DbSet<entitystorematerialised_CorePrescriptionroutes> entitystorematerialised_CorePrescriptionroutes { get; set; }
        public virtual DbSet<entitystorematerialised_CoreProblem> entitystorematerialised_CoreProblem { get; set; }
        public virtual DbSet<entitystorematerialised_CoreProcedure> entitystorematerialised_CoreProcedure { get; set; }
        public virtual DbSet<entitystorematerialised_CoreProceduredetail> entitystorematerialised_CoreProceduredetail { get; set; }
        public virtual DbSet<entitystorematerialised_CoreProceduredrains> entitystorematerialised_CoreProceduredrains { get; set; }
        public virtual DbSet<entitystorematerialised_CoreProcedurefinding> entitystorematerialised_CoreProcedurefinding { get; set; }
        public virtual DbSet<entitystorematerialised_CoreProcedurefluidloss> entitystorematerialised_CoreProcedurefluidloss { get; set; }
        public virtual DbSet<entitystorematerialised_CoreProcedureimplant> entitystorematerialised_CoreProcedureimplant { get; set; }
        public virtual DbSet<entitystorematerialised_CoreProcedureprovider> entitystorematerialised_CoreProcedureprovider { get; set; }
        public virtual DbSet<entitystorematerialised_CoreProcedurestructureaffected> entitystorematerialised_CoreProcedurestructureaffected { get; set; }
        public virtual DbSet<entitystorematerialised_CoreProvider> entitystorematerialised_CoreProvider { get; set; }
        public virtual DbSet<entitystorematerialised_CoreProvidercode> entitystorematerialised_CoreProvidercode { get; set; }
        public virtual DbSet<entitystorematerialised_CoreProviderteam> entitystorematerialised_CoreProviderteam { get; set; }
        public virtual DbSet<entitystorematerialised_CoreProviderteammembership> entitystorematerialised_CoreProviderteammembership { get; set; }
        public virtual DbSet<entitystorematerialised_CoreQuestion> entitystorematerialised_CoreQuestion { get; set; }
        public virtual DbSet<entitystorematerialised_CoreReferral> entitystorematerialised_CoreReferral { get; set; }
        public virtual DbSet<entitystorematerialised_CoreReferralattachment> entitystorematerialised_CoreReferralattachment { get; set; }
        public virtual DbSet<entitystorematerialised_CoreReferralprovider> entitystorematerialised_CoreReferralprovider { get; set; }
        public virtual DbSet<entitystorematerialised_CoreReport> entitystorematerialised_CoreReport { get; set; }
        public virtual DbSet<entitystorematerialised_CoreResult> entitystorematerialised_CoreResult { get; set; }
        public virtual DbSet<entitystorematerialised_CoreScore> entitystorematerialised_CoreScore { get; set; }
        public virtual DbSet<entitystorematerialised_CoreScoreparameter> entitystorematerialised_CoreScoreparameter { get; set; }
        public virtual DbSet<entitystorematerialised_CoreSpecialty> entitystorematerialised_CoreSpecialty { get; set; }
        public virtual DbSet<entitystorematerialised_CoreTask> entitystorematerialised_CoreTask { get; set; }
        public virtual DbSet<entitystorematerialised_CoreTheatresession> entitystorematerialised_CoreTheatresession { get; set; }
        public virtual DbSet<entitystorematerialised_CoreTheatresessionprovider> entitystorematerialised_CoreTheatresessionprovider { get; set; }
        public virtual DbSet<baseview_CristopherPersonwithids> baseview_CristopherPersonwithids { get; set; }
        public virtual DbSet<entitystorematerialised_DcsForm> entitystorematerialised_DcsForm { get; set; }
        public virtual DbSet<entitystorematerialised_DcsForminstance> entitystorematerialised_DcsForminstance { get; set; }
        public virtual DbSet<entitystorematerialised_DcsFormresponse> entitystorematerialised_DcsFormresponse { get; set; }
        public virtual DbSet<entitystorematerialised_DcsFormscore> entitystorematerialised_DcsFormscore { get; set; }
        public virtual DbSet<entitystorematerialised_DcsPatientregistration> entitystorematerialised_DcsPatientregistration { get; set; }
        public virtual DbSet<baseview_DemoDemocolortest> baseview_DemoDemocolortest { get; set; }
        public virtual DbSet<baseview_DemoDemosampleview1> baseview_DemoDemosampleview1 { get; set; }
        public virtual DbSet<baseview_DemoLocaldemosampleentity1view1> baseview_DemoLocaldemosampleentity1view1 { get; set; }
        public virtual DbSet<baseview_DemoPatientbanner> baseview_DemoPatientbanner { get; set; }
        public virtual DbSet<baseview_DemoPatientcontactdetails> baseview_DemoPatientcontactdetails { get; set; }
        public virtual DbSet<baseview_DemoPatientinfoc1> baseview_DemoPatientinfoc1 { get; set; }
        public virtual DbSet<baseview_DemoPerson> baseview_DemoPerson { get; set; }
        public virtual DbSet<baseview_DemoTest3> baseview_DemoTest3 { get; set; }
        public virtual DbSet<baseview_DemoVillageview> baseview_DemoVillageview { get; set; }
        public virtual DbSet<baseview_EboardsAllbeds> baseview_EboardsAllbeds { get; set; }
        public virtual DbSet<baseview_EboardsBcpexport> baseview_EboardsBcpexport { get; set; }
        public virtual DbSet<baseview_EboardsIma> baseview_EboardsIma { get; set; }
        public virtual DbSet<baseview_EboardsRecentpatients> baseview_EboardsRecentpatients { get; set; }
        public virtual DbSet<baseview_EboardsTcis> baseview_EboardsTcis { get; set; }
        public virtual DbSet<baseview_EboardsWardinformation> baseview_EboardsWardinformation { get; set; }
        public virtual DbSet<baseview_EboardsWardswithwaitingarea> baseview_EboardsWardswithwaitingarea { get; set; }
        public virtual DbSet<baseview_EboardsWardwaitingarea> baseview_EboardsWardwaitingarea { get; set; }
        public virtual DbSet<baseview_EpmaDischargedispensingdata> baseview_EpmaDischargedispensingdata { get; set; }
        public virtual DbSet<baseview_EpmaDischargesummarryhistory> baseview_EpmaDischargesummarryhistory { get; set; }
        public virtual DbSet<baseview_EpmaDischargesupplyrequest> baseview_EpmaDischargesupplyrequest { get; set; }
        public virtual DbSet<baseview_EpmaDispensingdata> baseview_EpmaDispensingdata { get; set; }
        public virtual DbSet<baseview_EpmaDoseevents> baseview_EpmaDoseevents { get; set; }
        public virtual DbSet<baseview_EpmaEncounters> baseview_EpmaEncounters { get; set; }
        public virtual DbSet<baseview_EpmaEpmaprescriptionhistory> baseview_EpmaEpmaprescriptionhistory { get; set; }
        public virtual DbSet<baseview_EpmaFrequentvtmunit> baseview_EpmaFrequentvtmunit { get; set; }
        public virtual DbSet<baseview_EpmaGetbpobservations> baseview_EpmaGetbpobservations { get; set; }
        public virtual DbSet<baseview_EpmaGetheightobservations> baseview_EpmaGetheightobservations { get; set; }
        public virtual DbSet<baseview_EpmaGetoxygenobservations> baseview_EpmaGetoxygenobservations { get; set; }
        public virtual DbSet<baseview_EpmaGetweightobservations> baseview_EpmaGetweightobservations { get; set; }
        public virtual DbSet<baseview_EpmaInfusionevents> baseview_EpmaInfusionevents { get; set; }
        public virtual DbSet<baseview_EpmaMedicationcodes> baseview_EpmaMedicationcodes { get; set; }
        public virtual DbSet<baseview_EpmaMedicationingredients> baseview_EpmaMedicationingredients { get; set; }
        public virtual DbSet<baseview_EpmaMedrecreview> baseview_EpmaMedrecreview { get; set; }
        public virtual DbSet<baseview_EpmaMedsonadmissionreview> baseview_EpmaMedsonadmissionreview { get; set; }
        public virtual DbSet<baseview_EpmaMedsondischargehistory> baseview_EpmaMedsondischargehistory { get; set; }
        public virtual DbSet<baseview_EpmaModonadmissionhistory> baseview_EpmaModonadmissionhistory { get; set; }
        public virtual DbSet<baseview_EpmaNursingadminlist> baseview_EpmaNursingadminlist { get; set; }
        public virtual DbSet<baseview_EpmaOrdersetprescription> baseview_EpmaOrdersetprescription { get; set; }
        public virtual DbSet<baseview_EpmaOrdersetprescriptiondetails> baseview_EpmaOrdersetprescriptiondetails { get; set; }
        public virtual DbSet<baseview_EpmaPharmacyreview> baseview_EpmaPharmacyreview { get; set; }
        public virtual DbSet<baseview_EpmaPoaprescriptions> baseview_EpmaPoaprescriptions { get; set; }
        public virtual DbSet<baseview_EpmaPrescriptiondetail> baseview_EpmaPrescriptiondetail { get; set; }
        public virtual DbSet<baseview_EpmaPrescriptiondetaildev> baseview_EpmaPrescriptiondetaildev { get; set; }
        public virtual DbSet<baseview_EpmaPrescriptionmeta> baseview_EpmaPrescriptionmeta { get; set; }
        public virtual DbSet<baseview_EpmaPrescriptionroutes> baseview_EpmaPrescriptionroutes { get; set; }
        public virtual DbSet<baseview_EpmaReviewhistory> baseview_EpmaReviewhistory { get; set; }
        public virtual DbSet<baseview_EpmaReviewhistorydev> baseview_EpmaReviewhistorydev { get; set; }
        public virtual DbSet<baseview_EpmaSupplyrequest> baseview_EpmaSupplyrequest { get; set; }
        public virtual DbSet<baseview_EpmaTherapyoverview> baseview_EpmaTherapyoverview { get; set; }
        public virtual DbSet<baseview_EpmaTherapyoverviewdev> baseview_EpmaTherapyoverviewdev { get; set; }
        public virtual DbSet<entitystorematerialised_ExtendedDiagnosis> entitystorematerialised_ExtendedDiagnosis { get; set; }
        public virtual DbSet<entitystorematerialised_ExtendedEncounter> entitystorematerialised_ExtendedEncounter { get; set; }
        public virtual DbSet<entitystorematerialised_ExtendedObservation> entitystorematerialised_ExtendedObservation { get; set; }
        public virtual DbSet<entitystorematerialised_ExtendedPerson> entitystorematerialised_ExtendedPerson { get; set; }
        public virtual DbSet<baseview_FluidbalanceCalculaterunningtotal> baseview_FluidbalanceCalculaterunningtotal { get; set; }
        public virtual DbSet<baseview_FluidbalanceCieventshistory> baseview_FluidbalanceCieventshistory { get; set; }
        public virtual DbSet<baseview_FluidbalanceCigetpreviousvalue> baseview_FluidbalanceCigetpreviousvalue { get; set; }
        public virtual DbSet<baseview_FluidbalanceContinuousinfusionnotcompleted> baseview_FluidbalanceContinuousinfusionnotcompleted { get; set; }
        public virtual DbSet<baseview_FluidbalanceFluidbalancesessionroutes> baseview_FluidbalanceFluidbalancesessionroutes { get; set; }
        public virtual DbSet<baseview_FluidbalanceGetallcontinuousinfusions> baseview_FluidbalanceGetallcontinuousinfusions { get; set; }
        public virtual DbSet<baseview_FluidbalanceGetdisplayorderforfluidbalanceroute> baseview_FluidbalanceGetdisplayorderforfluidbalanceroute { get; set; }
        public virtual DbSet<baseview_FluidbalanceGetweightobservations> baseview_FluidbalanceGetweightobservations { get; set; }
        public virtual DbSet<baseview_FluidbalanceUrineoutputhistory> baseview_FluidbalanceUrineoutputhistory { get; set; }
        public virtual DbSet<baseview_FormbuilderFormbuilderlist> baseview_FormbuilderFormbuilderlist { get; set; }
        public virtual DbSet<baseview_GpconnectAllallergyintolerance> baseview_GpconnectAllallergyintolerance { get; set; }
        public virtual DbSet<baseview_GpconnectAllmedications> baseview_GpconnectAllmedications { get; set; }
        public virtual DbSet<baseview_GpconnectDocumentreference> baseview_GpconnectDocumentreference { get; set; }
        public virtual DbSet<baseview_ListBinarycheckboxvalueswithcontext> baseview_ListBinarycheckboxvalueswithcontext { get; set; }
        public virtual DbSet<baseview_ListDatewithcontext> baseview_ListDatewithcontext { get; set; }
        public virtual DbSet<baseview_ListLongtextwithcontext> baseview_ListLongtextwithcontext { get; set; }
        public virtual DbSet<baseview_ListSelectradiovalueswithcontext> baseview_ListSelectradiovalueswithcontext { get; set; }
        public virtual DbSet<baseview_ListShorttextwithcontext> baseview_ListShorttextwithcontext { get; set; }
        public virtual DbSet<baseview_ListsAlllists> baseview_ListsAlllists { get; set; }
        public virtual DbSet<entitystorematerialised_LocalAneClinicalnotes> entitystorematerialised_LocalAneClinicalnotes { get; set; }
        public virtual DbSet<entitystorematerialised_LocalAneCoding> entitystorematerialised_LocalAneCoding { get; set; }
        public virtual DbSet<entitystorematerialised_LocalAneDesc> entitystorematerialised_LocalAneDesc { get; set; }
        public virtual DbSet<entitystorematerialised_LocalAneEncounter> entitystorematerialised_LocalAneEncounter { get; set; }
        public virtual DbSet<entitystorematerialised_LocalAneVendor> entitystorematerialised_LocalAneVendor { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofAdmintask> entitystorematerialised_LocalCofAdmintask { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofAdmintaskhistory> entitystorematerialised_LocalCofAdmintaskhistory { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofAppointment> entitystorematerialised_LocalCofAppointment { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofAttendancestatus> entitystorematerialised_LocalCofAttendancestatus { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofHl7messaging> entitystorematerialised_LocalCofHl7messaging { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupappointmentassignedto> entitystorematerialised_LocalCofLookupappointmentassignedto { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupappointmentattendstatus> entitystorematerialised_LocalCofLookupappointmentattendstatus { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupappointmentpriority> entitystorematerialised_LocalCofLookupappointmentpriority { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupappointmentreason> entitystorematerialised_LocalCofLookupappointmentreason { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupappointmentschedule> entitystorematerialised_LocalCofLookupappointmentschedule { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupappointmenttype> entitystorematerialised_LocalCofLookupappointmenttype { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupattendanceoutcome> entitystorematerialised_LocalCofLookupattendanceoutcome { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupclinicoutcome> entitystorematerialised_LocalCofLookupclinicoutcome { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupdecisiontotreatreason> entitystorematerialised_LocalCofLookupdecisiontotreatreason { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupdischargereason> entitystorematerialised_LocalCofLookupdischargereason { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupgeneral> entitystorematerialised_LocalCofLookupgeneral { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupinactivertt> entitystorematerialised_LocalCofLookupinactivertt { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookuplaterality> entitystorematerialised_LocalCofLookuplaterality { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupnextappointment> entitystorematerialised_LocalCofLookupnextappointment { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupprocedure> entitystorematerialised_LocalCofLookupprocedure { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupriskdescription> entitystorematerialised_LocalCofLookupriskdescription { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupriskflag> entitystorematerialised_LocalCofLookupriskflag { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookuprttpathwaytype> entitystorematerialised_LocalCofLookuprttpathwaytype { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupscheduleperriod> entitystorematerialised_LocalCofLookupscheduleperriod { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupsite> entitystorematerialised_LocalCofLookupsite { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookupspecialty> entitystorematerialised_LocalCofLookupspecialty { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofLookuptaskattendancemapping> entitystorematerialised_LocalCofLookuptaskattendancemapping { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofPersonrisk> entitystorematerialised_LocalCofPersonrisk { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofRecord> entitystorematerialised_LocalCofRecord { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofRttextract> entitystorematerialised_LocalCofRttextract { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofSubtype> entitystorematerialised_LocalCofSubtype { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofSystemattributes> entitystorematerialised_LocalCofSystemattributes { get; set; }
        public virtual DbSet<entitystorematerialised_LocalCofTreatment> entitystorematerialised_LocalCofTreatment { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemo1Exportentity1111> entitystorematerialised_LocalDemo1Exportentity1111 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemo1Exportentity2222> entitystorematerialised_LocalDemo1Exportentity2222 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemo1Exportentity3333> entitystorematerialised_LocalDemo1Exportentity3333 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemo1Exportentity4444> entitystorematerialised_LocalDemo1Exportentity4444 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemo1Exportentity6666> entitystorematerialised_LocalDemo1Exportentity6666 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemo1Newsampletoday> entitystorematerialised_LocalDemo1Newsampletoday { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoBedboard> entitystorematerialised_LocalDemoBedboard { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoBi> entitystorematerialised_LocalDemoBi { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoBloodpressure> entitystorematerialised_LocalDemoBloodpressure { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoBmitest> entitystorematerialised_LocalDemoBmitest { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoColor> entitystorematerialised_LocalDemoColor { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoCompany> entitystorematerialised_LocalDemoCompany { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoCountry> entitystorematerialised_LocalDemoCountry { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoCurrency> entitystorematerialised_LocalDemoCurrency { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoDemopatientdetails> entitystorematerialised_LocalDemoDemopatientdetails { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoDepartment> entitystorematerialised_LocalDemoDepartment { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoHardik> entitystorematerialised_LocalDemoHardik { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoIndiwardemo> entitystorematerialised_LocalDemoIndiwardemo { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoInfectiontimeline> entitystorematerialised_LocalDemoInfectiontimeline { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoLocaltest> entitystorematerialised_LocalDemoLocaltest { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoPeople> entitystorematerialised_LocalDemoPeople { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoRahul> entitystorematerialised_LocalDemoRahul { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoRelationtest> entitystorematerialised_LocalDemoRelationtest { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoRktestentity> entitystorematerialised_LocalDemoRktestentity { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoSachindemo> entitystorematerialised_LocalDemoSachindemo { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoSalford> entitystorematerialised_LocalDemoSalford { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoSample> entitystorematerialised_LocalDemoSample { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoSampleentity1> entitystorematerialised_LocalDemoSampleentity1 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoTaluk> entitystorematerialised_LocalDemoTaluk { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoTask> entitystorematerialised_LocalDemoTask { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoTest> entitystorematerialised_LocalDemoTest { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoTest2> entitystorematerialised_LocalDemoTest2 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoTestdemoone> entitystorematerialised_LocalDemoTestdemoone { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoTestentity> entitystorematerialised_LocalDemoTestentity { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoTestlocal1> entitystorematerialised_LocalDemoTestlocal1 { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoVendor> entitystorematerialised_LocalDemoVendor { get; set; }
        public virtual DbSet<entitystorematerialised_LocalDemoVillage> entitystorematerialised_LocalDemoVillage { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEboardsCurrentinpatients> entitystorematerialised_LocalEboardsCurrentinpatients { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEboardsEncounter> entitystorematerialised_LocalEboardsEncounter { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEboardsRecentpatients> entitystorematerialised_LocalEboardsRecentpatients { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEboardsTcis> entitystorematerialised_LocalEboardsTcis { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEboardsWaitingforbed> entitystorematerialised_LocalEboardsWaitingforbed { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEboardsWardinformation> entitystorematerialised_LocalEboardsWardinformation { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEpmaAdministrationwitness> entitystorematerialised_LocalEpmaAdministrationwitness { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEpmaBannerwarningoverrides> entitystorematerialised_LocalEpmaBannerwarningoverrides { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEpmaDischargesummarry> entitystorematerialised_LocalEpmaDischargesummarry { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEpmaMedreconciliation> entitystorematerialised_LocalEpmaMedreconciliation { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEpmaMedsonadmission> entitystorematerialised_LocalEpmaMedsonadmission { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEpmaMedsondischarge> entitystorematerialised_LocalEpmaMedsondischarge { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEpmaMoaprescriptions> entitystorematerialised_LocalEpmaMoaprescriptions { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEpmaModprescriptions> entitystorematerialised_LocalEpmaModprescriptions { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEpmaOrderset> entitystorematerialised_LocalEpmaOrderset { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEpmaOrdersetprescription> entitystorematerialised_LocalEpmaOrdersetprescription { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEpmaPatientwarnings> entitystorematerialised_LocalEpmaPatientwarnings { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEpmaPersonwarningupdate> entitystorematerialised_LocalEpmaPersonwarningupdate { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEpmaPrescriptionevent> entitystorematerialised_LocalEpmaPrescriptionevent { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEpmaPrescriptionmedicaitonsupply> entitystorematerialised_LocalEpmaPrescriptionmedicaitonsupply { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEpmaPrescriptionnursinginstructions> entitystorematerialised_LocalEpmaPrescriptionnursinginstructions { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEpmaPrescriptionreminders> entitystorematerialised_LocalEpmaPrescriptionreminders { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEpmaPrescriptionreviewstatus> entitystorematerialised_LocalEpmaPrescriptionreviewstatus { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEpmaSupplyrequest> entitystorematerialised_LocalEpmaSupplyrequest { get; set; }
        public virtual DbSet<entitystorematerialised_LocalEpmaWarnings> entitystorematerialised_LocalEpmaWarnings { get; set; }
        public virtual DbSet<entitystorematerialised_LocalGpconnectAllergyintolerance> entitystorematerialised_LocalGpconnectAllergyintolerance { get; set; }
        public virtual DbSet<entitystorematerialised_LocalGpconnectAllergymanifestation> entitystorematerialised_LocalGpconnectAllergymanifestation { get; set; }
        public virtual DbSet<entitystorematerialised_LocalGpconnectAllergyreaction> entitystorematerialised_LocalGpconnectAllergyreaction { get; set; }
        public virtual DbSet<entitystorematerialised_LocalGpconnectDocumentreference> entitystorematerialised_LocalGpconnectDocumentreference { get; set; }
        public virtual DbSet<entitystorematerialised_LocalGpconnectMedication> entitystorematerialised_LocalGpconnectMedication { get; set; }
        public virtual DbSet<entitystorematerialised_LocalGpconnectMedicationadministration> entitystorematerialised_LocalGpconnectMedicationadministration { get; set; }
        public virtual DbSet<entitystorematerialised_LocalGpconnectMedicationdispense> entitystorematerialised_LocalGpconnectMedicationdispense { get; set; }
        public virtual DbSet<entitystorematerialised_LocalGpconnectMedicationknowledge> entitystorematerialised_LocalGpconnectMedicationknowledge { get; set; }
        public virtual DbSet<entitystorematerialised_LocalGpconnectMedicationrequest> entitystorematerialised_LocalGpconnectMedicationrequest { get; set; }
        public virtual DbSet<entitystorematerialised_LocalGpconnectMedicationstatement> entitystorematerialised_LocalGpconnectMedicationstatement { get; set; }
        public virtual DbSet<entitystorematerialised_LocalInboundreferralGender> entitystorematerialised_LocalInboundreferralGender { get; set; }
        public virtual DbSet<entitystorematerialised_LocalInboundreferralProvider> entitystorematerialised_LocalInboundreferralProvider { get; set; }
        public virtual DbSet<entitystorematerialised_LocalInboundreferralReferralrequest> entitystorematerialised_LocalInboundreferralReferralrequest { get; set; }
        public virtual DbSet<entitystorematerialised_LocalInboundreferralSpecilaty> entitystorematerialised_LocalInboundreferralSpecilaty { get; set; }
        public virtual DbSet<entitystorematerialised_LocalLocaltest> entitystorematerialised_LocalLocaltest { get; set; }
        public virtual DbSet<entitystorematerialised_LocalLookupSpecialty> entitystorematerialised_LocalLookupSpecialty { get; set; }
        public virtual DbSet<entitystorematerialised_LocalPoaAssessmentsummary> entitystorematerialised_LocalPoaAssessmentsummary { get; set; }
        public virtual DbSet<entitystorematerialised_LocalPoaCommontask> entitystorematerialised_LocalPoaCommontask { get; set; }
        public virtual DbSet<entitystorematerialised_LocalPoaDose> entitystorematerialised_LocalPoaDose { get; set; }
        public virtual DbSet<entitystorematerialised_LocalPoaMedication> entitystorematerialised_LocalPoaMedication { get; set; }
        public virtual DbSet<entitystorematerialised_LocalPoaMedicationcodes> entitystorematerialised_LocalPoaMedicationcodes { get; set; }
        public virtual DbSet<entitystorematerialised_LocalPoaMedicationingredients> entitystorematerialised_LocalPoaMedicationingredients { get; set; }
        public virtual DbSet<entitystorematerialised_LocalPoaNote> entitystorematerialised_LocalPoaNote { get; set; }
        public virtual DbSet<entitystorematerialised_LocalPoaPosology> entitystorematerialised_LocalPoaPosology { get; set; }
        public virtual DbSet<entitystorematerialised_LocalPoaPreopassessment> entitystorematerialised_LocalPoaPreopassessment { get; set; }
        public virtual DbSet<entitystorematerialised_LocalPoaPrescription> entitystorematerialised_LocalPoaPrescription { get; set; }
        public virtual DbSet<entitystorematerialised_LocalPoaPrescriptionroutes> entitystorematerialised_LocalPoaPrescriptionroutes { get; set; }
        public virtual DbSet<entitystorematerialised_LocalPoaStaffgroup> entitystorematerialised_LocalPoaStaffgroup { get; set; }
        public virtual DbSet<entitystorematerialised_LocalPoaTask> entitystorematerialised_LocalPoaTask { get; set; }
        public virtual DbSet<entitystorematerialised_LocalPoaTaskreferredto> entitystorematerialised_LocalPoaTaskreferredto { get; set; }
        public virtual DbSet<entitystorematerialised_LocalPoaTaskstatus> entitystorematerialised_LocalPoaTaskstatus { get; set; }
        public virtual DbSet<entitystorematerialised_LocalPoaTasksummary> entitystorematerialised_LocalPoaTasksummary { get; set; }
        public virtual DbSet<entitystorematerialised_LocalPoaUsersettings> entitystorematerialised_LocalPoaUsersettings { get; set; }
        public virtual DbSet<entitystorematerialised_LocalRnohIntendedprocedure> entitystorematerialised_LocalRnohIntendedprocedure { get; set; }
        public virtual DbSet<entitystorematerialised_LocalRtsComment> entitystorematerialised_LocalRtsComment { get; set; }
        public virtual DbSet<entitystorematerialised_LocalRtsDocument> entitystorematerialised_LocalRtsDocument { get; set; }
        public virtual DbSet<entitystorematerialised_LocalRtsReferencedata> entitystorematerialised_LocalRtsReferencedata { get; set; }
        public virtual DbSet<entitystorematerialised_LocalRtsReferral> entitystorematerialised_LocalRtsReferral { get; set; }
        public virtual DbSet<entitystorematerialised_LocalScrubsDepartment> entitystorematerialised_LocalScrubsDepartment { get; set; }
        public virtual DbSet<entitystorematerialised_LocalScrubsPack> entitystorematerialised_LocalScrubsPack { get; set; }
        public virtual DbSet<entitystorematerialised_LocalScrubsPackitem> entitystorematerialised_LocalScrubsPackitem { get; set; }
        public virtual DbSet<entitystorematerialised_LocalScrubsStaffgroup> entitystorematerialised_LocalScrubsStaffgroup { get; set; }
        public virtual DbSet<entitystorematerialised_LocalScrubsStaffmember> entitystorematerialised_LocalScrubsStaffmember { get; set; }
        public virtual DbSet<entitystorematerialised_LocalScrubsStaffpackissue> entitystorematerialised_LocalScrubsStaffpackissue { get; set; }
        public virtual DbSet<entitystorematerialised_LocalSecambCad> entitystorematerialised_LocalSecambCad { get; set; }
        public virtual DbSet<entitystorematerialised_LocalSecambEpcr> entitystorematerialised_LocalSecambEpcr { get; set; }
        public virtual DbSet<entitystorematerialised_LocalSecambEpcramended> entitystorematerialised_LocalSecambEpcramended { get; set; }
        public virtual DbSet<entitystorematerialised_LocalTerminusForm> entitystorematerialised_LocalTerminusForm { get; set; }
        public virtual DbSet<entitystorematerialised_LocalTerminusFormfield> entitystorematerialised_LocalTerminusFormfield { get; set; }
        public virtual DbSet<entitystorematerialised_LocalTerminusFormsection> entitystorematerialised_LocalTerminusFormsection { get; set; }
        public virtual DbSet<entitystorematerialised_LocalTerminusMedicaltest> entitystorematerialised_LocalTerminusMedicaltest { get; set; }
        public virtual DbSet<entitystorematerialised_LocalTerminusModuledataversion> entitystorematerialised_LocalTerminusModuledataversion { get; set; }
        public virtual DbSet<entitystorematerialised_LocalTerminusSpvlog> entitystorematerialised_LocalTerminusSpvlog { get; set; }
        public virtual DbSet<entitystorematerialised_LocalTestMcc> entitystorematerialised_LocalTestMcc { get; set; }
        public virtual DbSet<entitystorematerialised_LocalTestWgtest> entitystorematerialised_LocalTestWgtest { get; set; }
        public virtual DbSet<entitystorematerialised_LocalUszDemoperson> entitystorematerialised_LocalUszDemoperson { get; set; }
        public virtual DbSet<entitystorematerialised_LocalWgTest123> entitystorematerialised_LocalWgTest123 { get; set; }
        public virtual DbSet<entitystorematerialised_MasterAccountmerges> entitystorematerialised_MasterAccountmerges { get; set; }
        public virtual DbSet<entitystorematerialised_MasterEncounter> entitystorematerialised_MasterEncounter { get; set; }
        public virtual DbSet<entitystorematerialised_MasterEncountermerges> entitystorematerialised_MasterEncountermerges { get; set; }
        public virtual DbSet<entitystorematerialised_MasterPerson> entitystorematerialised_MasterPerson { get; set; }
        public virtual DbSet<entitystorematerialised_MasterPersonmerges> entitystorematerialised_MasterPersonmerges { get; set; }
        public virtual DbSet<entitystorematerialised_MetaAdminpins> entitystorematerialised_MetaAdminpins { get; set; }
        public virtual DbSet<entitystorematerialised_MetaAllergycategory> entitystorematerialised_MetaAllergycategory { get; set; }
        public virtual DbSet<entitystorematerialised_MetaAllergyclinicalstatus> entitystorematerialised_MetaAllergyclinicalstatus { get; set; }
        public virtual DbSet<entitystorematerialised_MetaAllergycriticality> entitystorematerialised_MetaAllergycriticality { get; set; }
        public virtual DbSet<entitystorematerialised_MetaAllergyreportedbygroup> entitystorematerialised_MetaAllergyreportedbygroup { get; set; }
        public virtual DbSet<entitystorematerialised_MetaAllergyverificationstatus> entitystorematerialised_MetaAllergyverificationstatus { get; set; }
        public virtual DbSet<entitystorematerialised_MetaAnaesthetic> entitystorematerialised_MetaAnaesthetic { get; set; }
        public virtual DbSet<entitystorematerialised_MetaAntibiotics> entitystorematerialised_MetaAntibiotics { get; set; }
        public virtual DbSet<entitystorematerialised_MetaApplication> entitystorematerialised_MetaApplication { get; set; }
        public virtual DbSet<entitystorematerialised_MetaApplicationlist> entitystorematerialised_MetaApplicationlist { get; set; }
        public virtual DbSet<entitystorematerialised_MetaApplicationmodulemapping> entitystorematerialised_MetaApplicationmodulemapping { get; set; }
        public virtual DbSet<entitystorematerialised_MetaApplicationquestion> entitystorematerialised_MetaApplicationquestion { get; set; }
        public virtual DbSet<entitystorematerialised_MetaAssessmenttype> entitystorematerialised_MetaAssessmenttype { get; set; }
        public virtual DbSet<entitystorematerialised_MetaBedstatus> entitystorematerialised_MetaBedstatus { get; set; }
        public virtual DbSet<entitystorematerialised_MetaCarerecordtype> entitystorematerialised_MetaCarerecordtype { get; set; }
        public virtual DbSet<entitystorematerialised_MetaChart> entitystorematerialised_MetaChart { get; set; }
        public virtual DbSet<entitystorematerialised_MetaChartgraph> entitystorematerialised_MetaChartgraph { get; set; }
        public virtual DbSet<entitystorematerialised_MetaClinicalsummarystatuses> entitystorematerialised_MetaClinicalsummarystatuses { get; set; }
        public virtual DbSet<baseview_MetaCliniccontext> baseview_MetaCliniccontext { get; set; }
        public virtual DbSet<entitystorematerialised_MetaComplianceaid> entitystorematerialised_MetaComplianceaid { get; set; }
        public virtual DbSet<baseview_MetaConsultantcontext> baseview_MetaConsultantcontext { get; set; }
        public virtual DbSet<entitystorematerialised_MetaCurrentmedsprescriptionsource> entitystorematerialised_MetaCurrentmedsprescriptionsource { get; set; }
        public virtual DbSet<entitystorematerialised_MetaExpectedurineoutput> entitystorematerialised_MetaExpectedurineoutput { get; set; }
        public virtual DbSet<entitystorematerialised_MetaFluidbalanceiotype> entitystorematerialised_MetaFluidbalanceiotype { get; set; }
        public virtual DbSet<entitystorematerialised_MetaFluidbalancetimeslot> entitystorematerialised_MetaFluidbalancetimeslot { get; set; }
        public virtual DbSet<entitystorematerialised_MetaFluidbalancetype> entitystorematerialised_MetaFluidbalancetype { get; set; }
        public virtual DbSet<entitystorematerialised_MetaFluidcapturedevice> entitystorematerialised_MetaFluidcapturedevice { get; set; }
        public virtual DbSet<entitystorematerialised_MetaFormbuildercategory> entitystorematerialised_MetaFormbuildercategory { get; set; }
        public virtual DbSet<entitystorematerialised_MetaFormbuilderform> entitystorematerialised_MetaFormbuilderform { get; set; }
        public virtual DbSet<entitystorematerialised_MetaFormbuildersubcategory> entitystorematerialised_MetaFormbuildersubcategory { get; set; }
        public virtual DbSet<entitystorematerialised_MetaFormbuildersystemtemplate> entitystorematerialised_MetaFormbuildersystemtemplate { get; set; }
        public virtual DbSet<entitystorematerialised_MetaFormbuildersystemtype> entitystorematerialised_MetaFormbuildersystemtype { get; set; }
        public virtual DbSet<entitystorematerialised_MetaFormsection> entitystorematerialised_MetaFormsection { get; set; }
        public virtual DbSet<entitystorematerialised_MetaFormsectionquestion> entitystorematerialised_MetaFormsectionquestion { get; set; }
        public virtual DbSet<entitystorematerialised_MetaFormtype> entitystorematerialised_MetaFormtype { get; set; }
        public virtual DbSet<entitystorematerialised_MetaGraph> entitystorematerialised_MetaGraph { get; set; }
        public virtual DbSet<entitystorematerialised_MetaGraphband> entitystorematerialised_MetaGraphband { get; set; }
        public virtual DbSet<baseview_MetaGraphcharts> baseview_MetaGraphcharts { get; set; }
        public virtual DbSet<entitystorematerialised_MetaGraphparameterkey> entitystorematerialised_MetaGraphparameterkey { get; set; }
        public virtual DbSet<entitystorematerialised_MetaGraphscale> entitystorematerialised_MetaGraphscale { get; set; }
        public virtual DbSet<entitystorematerialised_MetaInfusiontype> entitystorematerialised_MetaInfusiontype { get; set; }
        public virtual DbSet<entitystorematerialised_MetaListcontexts> entitystorematerialised_MetaListcontexts { get; set; }
        public virtual DbSet<entitystorematerialised_MetaLocationtype> entitystorematerialised_MetaLocationtype { get; set; }
        public virtual DbSet<entitystorematerialised_MetaModule> entitystorematerialised_MetaModule { get; set; }
        public virtual DbSet<baseview_MetaModulelist> baseview_MetaModulelist { get; set; }
        public virtual DbSet<entitystorematerialised_MetaObservationchartsettings> entitystorematerialised_MetaObservationchartsettings { get; set; }
        public virtual DbSet<entitystorematerialised_MetaObservationscaletype> entitystorematerialised_MetaObservationscaletype { get; set; }
        public virtual DbSet<entitystorematerialised_MetaObservationtype> entitystorematerialised_MetaObservationtype { get; set; }
        public virtual DbSet<entitystorematerialised_MetaObservationtypemeasurement> entitystorematerialised_MetaObservationtypemeasurement { get; set; }
        public virtual DbSet<entitystorematerialised_MetaOrdercategory> entitystorematerialised_MetaOrdercategory { get; set; }
        public virtual DbSet<entitystorematerialised_MetaOxygendevices> entitystorematerialised_MetaOxygendevices { get; set; }
        public virtual DbSet<entitystorematerialised_MetaOxygenprescriptionadditionalinfo> entitystorematerialised_MetaOxygenprescriptionadditionalinfo { get; set; }
        public virtual DbSet<entitystorematerialised_MetaPersona> entitystorematerialised_MetaPersona { get; set; }
        public virtual DbSet<baseview_MetaPersona1> baseview_MetaPersona1 { get; set; }
        public virtual DbSet<entitystorematerialised_MetaPersonacontext> entitystorematerialised_MetaPersonacontext { get; set; }
        public virtual DbSet<entitystorematerialised_MetaPersonacontextgroup> entitystorematerialised_MetaPersonacontextgroup { get; set; }
        public virtual DbSet<entitystorematerialised_MetaPersonacontextgroupusers> entitystorematerialised_MetaPersonacontextgroupusers { get; set; }
        public virtual DbSet<entitystorematerialised_MetaPersonacontextmappingcodes> entitystorematerialised_MetaPersonacontextmappingcodes { get; set; }
        public virtual DbSet<entitystorematerialised_MetaPositioning> entitystorematerialised_MetaPositioning { get; set; }
        public virtual DbSet<entitystorematerialised_MetaPrescriptionadditionalconditions> entitystorematerialised_MetaPrescriptionadditionalconditions { get; set; }
        public virtual DbSet<entitystorematerialised_MetaPrescriptioncontext> entitystorematerialised_MetaPrescriptioncontext { get; set; }
        public virtual DbSet<entitystorematerialised_MetaPrescriptionduration> entitystorematerialised_MetaPrescriptionduration { get; set; }
        public virtual DbSet<entitystorematerialised_MetaPrescriptionfrequency> entitystorematerialised_MetaPrescriptionfrequency { get; set; }
        public virtual DbSet<entitystorematerialised_MetaPrescriptionordersettype> entitystorematerialised_MetaPrescriptionordersettype { get; set; }
        public virtual DbSet<entitystorematerialised_MetaPrescriptionsource> entitystorematerialised_MetaPrescriptionsource { get; set; }
        public virtual DbSet<entitystorematerialised_MetaPrescriptionstatus> entitystorematerialised_MetaPrescriptionstatus { get; set; }
        public virtual DbSet<entitystorematerialised_MetaProviderrole> entitystorematerialised_MetaProviderrole { get; set; }
        public virtual DbSet<entitystorematerialised_MetaReviewstatus> entitystorematerialised_MetaReviewstatus { get; set; }
        public virtual DbSet<entitystorematerialised_MetaRoute> entitystorematerialised_MetaRoute { get; set; }
        public virtual DbSet<entitystorematerialised_MetaRouteconfig> entitystorematerialised_MetaRouteconfig { get; set; }
        public virtual DbSet<entitystorematerialised_MetaRoutetype> entitystorematerialised_MetaRoutetype { get; set; }
        public virtual DbSet<entitystorematerialised_MetaRoutetypefluidcapturedevice> entitystorematerialised_MetaRoutetypefluidcapturedevice { get; set; }
        public virtual DbSet<entitystorematerialised_MetaSepsistask> entitystorematerialised_MetaSepsistask { get; set; }
        public virtual DbSet<entitystorematerialised_MetaSynchronouspostlockid> entitystorematerialised_MetaSynchronouspostlockid { get; set; }
        public virtual DbSet<entitystorematerialised_MetaTerminusform> entitystorematerialised_MetaTerminusform { get; set; }
        public virtual DbSet<baseview_MetaTheatrecontext> baseview_MetaTheatrecontext { get; set; }
        public virtual DbSet<entitystorematerialised_MetaWard> entitystorematerialised_MetaWard { get; set; }
        public virtual DbSet<entitystorematerialised_MetaWardbay> entitystorematerialised_MetaWardbay { get; set; }
        public virtual DbSet<entitystorematerialised_MetaWardbaybed> entitystorematerialised_MetaWardbaybed { get; set; }
        public virtual DbSet<entitystorematerialised_MetaWardwithoutbed> entitystorematerialised_MetaWardwithoutbed { get; set; }
        public virtual DbSet<entitystorematerialised_MetaWarningscoresystem> entitystorematerialised_MetaWarningscoresystem { get; set; }
        public virtual DbSet<entitystorematerialised_MetaWeightbearingstatus> entitystorematerialised_MetaWeightbearingstatus { get; set; }
        public virtual DbSet<baseview_MsTest> baseview_MsTest { get; set; }
        public virtual DbSet<baseview_MsTest2> baseview_MsTest2 { get; set; }
        public virtual DbSet<baseview_MsTest4> baseview_MsTest4 { get; set; }
        public virtual DbSet<baseview_NhsersGetersworklist> baseview_NhsersGetersworklist { get; set; }
        public virtual DbSet<baseview_PatientbannerColumn2> baseview_PatientbannerColumn2 { get; set; }
        public virtual DbSet<baseview_PatientbannerMainallergies> baseview_PatientbannerMainallergies { get; set; }
        public virtual DbSet<baseview_PatientbannerMainbadges> baseview_PatientbannerMainbadges { get; set; }
        public virtual DbSet<baseview_PatientbannerMainbanner> baseview_PatientbannerMainbanner { get; set; }
        public virtual DbSet<baseview_PatientbannerMaindemographics> baseview_PatientbannerMaindemographics { get; set; }
        public virtual DbSet<baseview_PatientbannerMainencounter> baseview_PatientbannerMainencounter { get; set; }
        public virtual DbSet<baseview_PatientbannerMainwarnings> baseview_PatientbannerMainwarnings { get; set; }
        public virtual DbSet<baseview_PatientbannerModalpatientbanner> baseview_PatientbannerModalpatientbanner { get; set; }
        public virtual DbSet<baseview_PatientbannerPersonaddress> baseview_PatientbannerPersonaddress { get; set; }
        public virtual DbSet<baseview_PatientbannerPersonatrisk> baseview_PatientbannerPersonatrisk { get; set; }
        public virtual DbSet<baseview_PatientbannerPersoncontactinfo> baseview_PatientbannerPersoncontactinfo { get; set; }
        public virtual DbSet<baseview_PatientbannerPersoninfo> baseview_PatientbannerPersoninfo { get; set; }
        public virtual DbSet<baseview_PatientbannerPersonobservation> baseview_PatientbannerPersonobservation { get; set; }
        public virtual DbSet<baseview_PoaAllergylist> baseview_PoaAllergylist { get; set; }
        public virtual DbSet<baseview_PoaAssessmentlist> baseview_PoaAssessmentlist { get; set; }
        public virtual DbSet<baseview_PoaFormhistory> baseview_PoaFormhistory { get; set; }
        public virtual DbSet<baseview_PoaLinkedencounters> baseview_PoaLinkedencounters { get; set; }
        public virtual DbSet<baseview_PoaMedicationcodes> baseview_PoaMedicationcodes { get; set; }
        public virtual DbSet<baseview_PoaMedicationingredients> baseview_PoaMedicationingredients { get; set; }
        public virtual DbSet<baseview_PoaNotecount> baseview_PoaNotecount { get; set; }
        public virtual DbSet<baseview_PoaPatientbanner> baseview_PoaPatientbanner { get; set; }
        public virtual DbSet<baseview_PoaPoanotes> baseview_PoaPoanotes { get; set; }
        public virtual DbSet<baseview_PoaPoatasks> baseview_PoaPoatasks { get; set; }
        public virtual DbSet<baseview_PoaPrescriptionroutes> baseview_PoaPrescriptionroutes { get; set; }
        public virtual DbSet<baseview_PoaScheduledoperations> baseview_PoaScheduledoperations { get; set; }
        public virtual DbSet<baseview_PoaTasksnotcompleted> baseview_PoaTasksnotcompleted { get; set; }
        public virtual DbSet<baseview_PoaYearlist> baseview_PoaYearlist { get; set; }
        public virtual DbSet<baseview_RbacActions> baseview_RbacActions { get; set; }
        public virtual DbSet<baseview_RbacApplications> baseview_RbacApplications { get; set; }
        public virtual DbSet<baseview_RbacList> baseview_RbacList { get; set; }
        public virtual DbSet<baseview_RbacModule> baseview_RbacModule { get; set; }
        public virtual DbSet<baseview_RbacPersona> baseview_RbacPersona { get; set; }
        public virtual DbSet<baseview_RtsComments> baseview_RtsComments { get; set; }
        public virtual DbSet<baseview_SecambCad> baseview_SecambCad { get; set; }
        public virtual DbSet<baseview_SecambEpcr> baseview_SecambEpcr { get; set; }
        public virtual DbSet<baseview_TerminologyAnaesthetics> baseview_TerminologyAnaesthetics { get; set; }
        public virtual DbSet<baseview_TerminologyApproach> baseview_TerminologyApproach { get; set; }
        public virtual DbSet<entitystorematerialised_TerminologyAttributedefinition> entitystorematerialised_TerminologyAttributedefinition { get; set; }
        public virtual DbSet<baseview_TerminologyBodyfluids> baseview_TerminologyBodyfluids { get; set; }
        public virtual DbSet<baseview_TerminologyBodystructure> baseview_TerminologyBodystructure { get; set; }
        public virtual DbSet<baseview_TerminologyBodystructureaffectedas> baseview_TerminologyBodystructureaffectedas { get; set; }
        public virtual DbSet<entitystorematerialised_TerminologyConcept> entitystorematerialised_TerminologyConcept { get; set; }
        public virtual DbSet<entitystorematerialised_TerminologyConceptancestor> entitystorematerialised_TerminologyConceptancestor { get; set; }
        public virtual DbSet<entitystorematerialised_TerminologyConceptclass> entitystorematerialised_TerminologyConceptclass { get; set; }
        public virtual DbSet<entitystorematerialised_TerminologyConceptrelationship> entitystorematerialised_TerminologyConceptrelationship { get; set; }
        public virtual DbSet<entitystorematerialised_TerminologyConceptsynonym> entitystorematerialised_TerminologyConceptsynonym { get; set; }
        public virtual DbSet<baseview_TerminologyDeepclosure> baseview_TerminologyDeepclosure { get; set; }
        public virtual DbSet<baseview_TerminologyDiagnoses> baseview_TerminologyDiagnoses { get; set; }
        public virtual DbSet<entitystorematerialised_TerminologyDomain> entitystorematerialised_TerminologyDomain { get; set; }
        public virtual DbSet<baseview_TerminologyDressings> baseview_TerminologyDressings { get; set; }
        public virtual DbSet<entitystorematerialised_TerminologyDrugstrength> entitystorematerialised_TerminologyDrugstrength { get; set; }
        public virtual DbSet<baseview_TerminologyFindings> baseview_TerminologyFindings { get; set; }
        public virtual DbSet<baseview_TerminologyIndications> baseview_TerminologyIndications { get; set; }
        public virtual DbSet<baseview_TerminologyMarginassessments> baseview_TerminologyMarginassessments { get; set; }
        public virtual DbSet<baseview_TerminologyOperationantibiotics> baseview_TerminologyOperationantibiotics { get; set; }
        public virtual DbSet<baseview_TerminologyPositioning> baseview_TerminologyPositioning { get; set; }
        public virtual DbSet<baseview_TerminologyProblems> baseview_TerminologyProblems { get; set; }
        public virtual DbSet<baseview_TerminologyProcedures> baseview_TerminologyProcedures { get; set; }
        public virtual DbSet<entitystorematerialised_TerminologyRelationship> entitystorematerialised_TerminologyRelationship { get; set; }
        public virtual DbSet<baseview_TerminologySkinclosure> baseview_TerminologySkinclosure { get; set; }
        public virtual DbSet<baseview_TerminologySkinincision> baseview_TerminologySkinincision { get; set; }
        public virtual DbSet<baseview_TerminologySkinpreparation> baseview_TerminologySkinpreparation { get; set; }
        public virtual DbSet<baseview_TerminologySkinrepairedwith> baseview_TerminologySkinrepairedwith { get; set; }
        public virtual DbSet<entitystorematerialised_TerminologySourcetoconceptmap> entitystorematerialised_TerminologySourcetoconceptmap { get; set; }
        public virtual DbSet<entitystorematerialised_TerminologyVocabulary> entitystorematerialised_TerminologyVocabulary { get; set; }
        public virtual DbSet<baseview_TerminologyVolumeunit> baseview_TerminologyVolumeunit { get; set; }
        public virtual DbSet<baseview_TerminologyWeightbearingstatus> baseview_TerminologyWeightbearingstatus { get; set; }
        public virtual DbSet<baseview_TerminusAllinpatients> baseview_TerminusAllinpatients { get; set; }
        public virtual DbSet<baseview_TerminusAllinpatientswithhighews> baseview_TerminusAllinpatientswithhighews { get; set; }
        public virtual DbSet<baseview_TerminusAllpatientswithobservationsdueoroverdue> baseview_TerminusAllpatientswithobservationsdueoroverdue { get; set; }
        public virtual DbSet<baseview_TerminusBplastrecorded> baseview_TerminusBplastrecorded { get; set; }
        public virtual DbSet<entitystorematerialised_TerminusJustt123> entitystorematerialised_TerminusJustt123 { get; set; }
        public virtual DbSet<baseview_TerminusMycurrentinpatients> baseview_TerminusMycurrentinpatients { get; set; }
        public virtual DbSet<entitystorematerialised_TerminusMypatients> entitystorematerialised_TerminusMypatients { get; set; }
        public virtual DbSet<baseview_TerminusPatientbanner> baseview_TerminusPatientbanner { get; set; }
        public virtual DbSet<entitystorematerialised_TerminusPatientlist> entitystorematerialised_TerminusPatientlist { get; set; }
        public virtual DbSet<baseview_TerminusPatientlist1> baseview_TerminusPatientlist1 { get; set; }
        public virtual DbSet<baseview_TerminusPatientlists> baseview_TerminusPatientlists { get; set; }
        public virtual DbSet<baseview_TerminusPatientsearch> baseview_TerminusPatientsearch { get; set; }
        public virtual DbSet<baseview_TerminusPersonallergylist> baseview_TerminusPersonallergylist { get; set; }
        public virtual DbSet<entitystorematerialised_TerminusPersonpatientlist> entitystorematerialised_TerminusPersonpatientlist { get; set; }
        public virtual DbSet<baseview_TerminusPersonswithids> baseview_TerminusPersonswithids { get; set; }
        public virtual DbSet<baseview_TerminusSepsisinpatient> baseview_TerminusSepsisinpatient { get; set; }
        public virtual DbSet<baseview_TerminusSpvobservations> baseview_TerminusSpvobservations { get; set; }
        public virtual DbSet<baseview_TerminusSpvobservationsbyevent> baseview_TerminusSpvobservationsbyevent { get; set; }
        public virtual DbSet<baseview_TerminusSpvobservationsbyeventchart> baseview_TerminusSpvobservationsbyeventchart { get; set; }
        public virtual DbSet<entitystorematerialised_TerminusTestterm> entitystorematerialised_TerminusTestterm { get; set; }
        public virtual DbSet<baseview_TestJsont> baseview_TestJsont { get; set; }
        public virtual DbSet<entitystorematerialised_TestObservation> entitystorematerialised_TestObservation { get; set; }
        public virtual DbSet<baseview_TestObshcart3> baseview_TestObshcart3 { get; set; }
        public virtual DbSet<baseview_TestTest> baseview_TestTest { get; set; }
        public virtual DbSet<baseview_WgTest> baseview_WgTest { get; set; }
        public virtual DbSet<baseview_WgTest2> baseview_WgTest2 { get; set; }
        public virtual DbSet<baseview_WgTest3> baseview_WgTest3 { get; set; }
    }
}
